APP-99856 jpc install instructions
pendo-io/pendo-mobile-sdk pull request #149
Opened 2024-07-01 07:27 UTC by randmaayan

2024-07-01 07:36 UTC, udilevin reviewed
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: 3 of 4 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-01 13:05 UTC, noambartouv requested changes
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: 3 of 4 files reviewed, 15 unresolved discussions (waiting on @randmaayan and @udilevin)

___
*[`android/pnddocs/jetpackCompose_instructions.md` line 1 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iJg-Q1ENWzYXCUhpT:-O0iJg-Q1ENWzYXCUhpU:bpf02j1) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L1)):*
> ```Markdown
> # Jetpack Compose 
> ```

Do we need an install instructions link from the main github page? (https://github.com/pendo-io/pendo-mobile-sdk)
If yes, we need how to present it in the install instructions, considering this may cause confusion in regards to iOS with support for SwiftUI. Perhaps we should split Android and iOS or explicitly mention UIKit + SwiftUI in regards to iOS
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 1 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iLc6iE-Ue8WkrRnlz:-O0iLc6iE-Ue8WkrRnm-:b-dj53dy) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L1)):*
> ```Markdown
> # Jetpack Compose 
> ```

Please rename file to match styling of other file names jetpack_compose.md (add beta? I'm assuming the article will be combined and removed once we go GA)
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 2 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iJCqe-2htSBhMERJw:-O0iJCqf2hTV82Gm6EU-:b-v7xm86) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L2)):*
> ```Markdown
> # Jetpack Compose 
> ```

Please add a warning alert here at the top stating that non-track event support is in beta
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 6 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iIlnJ6qOrcU2gEsOQ:-O0iIlnJ6qOrcU2gEsOR:bwoc9sg) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L6)):*
> ```Markdown
> >Starting **SDK 3.3**, Pendo support for Jetpack Compose includes the following -
> >- Code-based tooltips
> >- Retroactive Page View analytics and page view activated guides. Please see integration instructions below.
> ```

I would move codeless things to the top of the list of content
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 6 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iMR5hCzklkB62tP2t:-O0iMR5hCzklkB62tP2u:b-vs2mdx) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L6)):*
> ```Markdown
> >Starting **SDK 3.3**, Pendo support for Jetpack Compose includes the following -
> >- Code-based tooltips
> >- Retroactive Page View analytics and page view activated guides. Please see integration instructions below.
> ```

"Please see integration instructions below" is redundant in my opinion. Also below are the requirements, so its a bit funny
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 17 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iMC_A6I81139_VnYd:-O0iMC_A6I81139_VnYe:b9djkjk) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L17)):*
> ```Markdown
> 
> 
> ## Step 1. Install Pendo SDK as instructed for Android Native Apps [here](https://github.com/pendo-io/pendo-mobile-sdk/blob/master/android/pnddocs/native-android.md)
> ```

Looking at the article, the here looks weird at the end of the line. I think move it to a new line 
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 21 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iMi6b7upf1rjs_5AN:-O0iMi6b7upf1rjs_5AO:bug9v3i) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L21)):*
> ```Markdown
> ## Step 2. Add the JetpackComposeBeta flag
>     
>     Add the following PendoOptions object to the Pendo Setup API call from Step 1:
> ```

Look at the article the first sentence is also part of the code block when it shouldn't be
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 37 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iMpT2A7y8DniY8t71:-O0iMpT2A7y8DniY8t72:bug9v3i) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L37)):*
> ```Markdown
> ## Step 2. Add the pendoTag
> 
>     In your application code, for each Composable component that you would like to present a tooltip on, add the following snippet:
> ```

Look at the article the first sentence is also part of the code block when it shouldn't be
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 40 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iN1fm2cLABEKf1WBq:-O0iN1fm2cLABEKf1WBr:b-24dctd) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L40)):*
> ```Markdown
> 
>     ```kotlin
>         someComposableObject(
> ```

I think remove all the new lines
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 50 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iN8i5Dc1dz_PkG1s3:-O0iN8i5Dc1dz_PkG1s4:b-fagpkq) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L50)):*
> ```Markdown
> 
> ## Step 3. Add Compose Navigation Support
>     If you are using a **Compose Navigation**, please add the following as soon as possible, right after `rememberNavController` in your app.
> ```

This line is being considered as part of the header
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 54 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iNRBL43sOjBEoiyYL:-O0iNRBL43sOjBEoiyYM:b-6rgzc5) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L54)):*
> ```Markdown
> 
> >[!NOTE]
> >- Without this step, Pendo will not be able to recognize Compose pages in your app.
> ```

Bullets without a sentence before look funny. I think have the note as sentences one after the other
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 55 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iOF9U-6oyGGHs2Xj4:-O0iOF9U-6oyGGHs2Xj5:b-h3laks) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L55)):*
> ```Markdown
> >[!NOTE]
> >- Without this step, Pendo will not be able to recognize Compose pages in your app.
> >- Navigator is limited to `androidx.navigation:navigation-compose`
> ```

This is not a full sentence. The Navigator or The navigation ... ?
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 58 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iO9c2B_Axt8OueMEZ:-O0iO9c2B_Axt8OueME_:b535xo9) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L58)):*
> ```Markdown
> 
> 
>     ```kotlin
> ```

the word kotlin shows
___
*[`android/pnddocs/native-android.md` line 7 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iHyr74Q84LGQnDWcb:-O0iHyr74Q84LGQnDWcc:bomc981) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b7 [...]

2024-07-01 15:30 UTC, randmaayan reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: 2 of 4 files reviewed, 10 unresolved discussions (waiting on @naorlevi, @noambartouv, and @udilevin)

___
*[`android/pnddocs/native-android.md` line 7 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iHyr74Q84LGQnDWcb:-O0itGnU02aeNQxsAdmn:b-pze3k1) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/native-android.md#L7)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

1. The sentence is hard to digest. I suggest stating what is supported codeless, then move on to code-based then state that for everything else we have track events.  
2. Also isn't this a beta? It should be stated if that's the case
</blockquote></details>

1. please take a look. 
2. done. 
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 1 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iLc6iE-Ue8WkrRnlz:-O0irTroCLLL-o73GT2T:b-aqlc5f) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L1)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Please rename file to match styling of other file names jetpack_compose.md (add beta? I'm assuming the article will be combined and removed once we go GA)
</blockquote></details>

changed to jetpack_compose-android.md for now.
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 1 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iJg-Q1ENWzYXCUhpT:-O0isrGCBlix6Wrxa90z:b4f3i6p) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L1)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Do we need an install instructions link from the main github page? (https://github.com/pendo-io/pendo-mobile-sdk)
If yes, we need how to present it in the install instructions, considering this may cause confusion in regards to iOS with support for SwiftUI. Perhaps we should split Android and iOS or explicitly mention UIKit + SwiftUI in regards to iOS
</blockquote></details>

Well, it is Android native, and this way we make sure they are correctly reading the instructions in order, but, I don't mind changing it if someone thinks otherwise. 

@naorlevi  ? thoughts? 
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 2 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iJCqe-2htSBhMERJw:-O0is9go70EbaFf7oPNZ:b-8b50g8) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L2)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Please add a warning alert here at the top stating that non-track event support is in beta
</blockquote></details>

please take a look. 
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 6 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iMR5hCzklkB62tP2t:-O0ig4Cr58NFTrhhNz6L:b6p80q5) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L6)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

"Please see integration instructions below" is redundant in my opinion. Also below are the requirements, so its a bit funny
</blockquote></details>

removed. 
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 17 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iMC_A6I81139_VnYd:-O0ifZfO78p9iZTn9_Or:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L17)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Looking at the article, the here looks weird at the end of the line. I think move it to a new line
</blockquote></details>

Done.
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 37 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iMpT2A7y8DniY8t71:-O0ifOE758wJwFgQdJvk:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L37)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Look at the article the first sentence is also part of the code block when it shouldn't be
</blockquote></details>

Done.
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 40 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iN1fm2cLABEKf1WBq:-O0ie9GaDSh8VOFXjeR3:b-sglpcq) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L40)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

I think remove all the new lines
</blockquote></details>

example below of how the IDE indents. leaving it as is. 



_Code snippet:_
```Markdown
Column(
    modifier = Modifier
        .clickable(onClick = { onSnackClick(snack.id) })
        .fillMaxSize()
) {
```
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 50 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iN8i5Dc1dz_PkG1s3:-O0ifbSx7EW9Bm-ZcgR9:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L50)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

This line is being considered as part of the header
</blockquote></details>

Done.
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 55 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iOF9U-6oyGGHs2Xj4:-O0ifchW-TvAf16zp2td:b-1swrnj) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L55)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

This is not a full sentence. The Navigator or The navigation ... ?
</blockquote></details>

is this better


<!-- Sent from Reviewable.io -->

2024-07-01 19:03 UTC, noambartouv requested changes
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @naorlevi, @randmaayan, and @udilevin)

___
*[`android/pnddocs/jetpack_compose-android.md` line 1 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0jbrc6-OlFEyk7ubC3:-O0jbrc6-OlFEyk7ubC4:b5wvwx7) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/929fde942ee058001576ae0e3beae9e7c62cd270/android/pnddocs/jetpack_compose-android.md#L1)):*
> ```Markdown
> # Jetpack Compose 
> ```

Suggesting to add the "(Beta)" to the title at the top of page as well to make it as clear as possible so "Jetpack Compose (Beta)"
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 1 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iJg-Q1ENWzYXCUhpT:-O0jc1SJCM09zgy6R9Kl:b-cxy9qy) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L1)):*
<details><summary><i>Previously, randmaayan wrote…</i></summary><blockquote>

Well, it is Android native, and this way we make sure they are correctly reading the instructions in order, but, I don't mind changing it if someone thinks otherwise. 

@naorlevi  ? thoughts?
</blockquote></details>

Navigating to this article via a small link in the android native instructions will lead to a big drop off rate. If this is truly open beta and we want people to interact with it then we need to make it as visible as possible and place it where the users expect it (could be more than one place) - in our github that is clearly the main page with all the other installation instructions and perhaps you are right we should also link from the view based instructions (but this is secondary). You will have a big drop off of users reaching it by placing it as a small link in an alert inside the android native article.

By moving it to the main, though, we need to make sure everything remains clear. I think we will introduce an issue regarding view-based vs JPC beta, and it will also raise confusion around iOS since UIKit and SwiftUI aren't mentioned while JPC will be. We need to address those issues - we can brainstorm on this together to think of solutions
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 2 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iJCqe-2htSBhMERJw:-O0jfHTzEbrkOwrE97Wx:bmch946) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L2)):*
<details><summary><i>Previously, randmaayan wrote…</i></summary><blockquote>

please take a look.
</blockquote></details>

I would change the alert from IMPORTANT to WARNING. That's my opinion but maybe worth getting a crowd vote on this


<!-- Sent from Reviewable.io -->

2024-07-01 19:08 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @naorlevi, @randmaayan, and @udilevin)

___
*[`android/pnddocs/native-android.md` line 7 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iLK_A7nbJm6EHWpal:-O0jgX0h1U6B3mti1h0Z:b6uk1bj) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/native-android.md#L7)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

link is broken when I tried it :thinking:
</blockquote></details>

I think link will only work once merged. Just right yourself a reminder to test when we do 🙂
___
*[`android/pnddocs/jetpack_compose-android.md` line 81 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0jfoYQB9v0I-7mywwR:-O0jfoYQB9v0I-7mywwS:b-wkpxp6) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/929fde942ee058001576ae0e3beae9e7c62cd270/android/pnddocs/jetpack_compose-android.md#L81)):*
> ```Markdown
> 
> ## Step 4. Mobile device connectivity for tagging and testing
> Please follow the instructions as instructed for Android Native Apps [here](https://github.com/pendo-io/pendo-mobile-sdk/blob/master/android/pnddocs/native-android.md)
> ```

You can link to a specific section in the article. So in this case:
https://github.com/pendo-io/pendo-mobile-sdk/blob/master/android/pnddocs/native-android.md#step-3-mobile-device-connectivity-for-tagging-and-testing


<!-- Sent from Reviewable.io -->

2024-07-01 19:10 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @naorlevi, @randmaayan, and @udilevin)

___
*[`android/pnddocs/jetpack_compose-android.md` line 54 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0jh-rv1cv4ABtQqRTp:-O0jh-rv1cv4ABtQqRTq:b6uwtgg) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/929fde942ee058001576ae0e3beae9e7c62cd270/android/pnddocs/jetpack_compose-android.md#L54)):*
> ```Markdown
> >pendoTags are case-sensitive. 
> 
> ## Step 3. Add Compose Navigation Support
> ```

I think this step should be before pendoTag - I would swap steps 2 and 3


<!-- Sent from Reviewable.io -->

2024-07-01 19:14 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: 2 of 4 files reviewed, 9 unresolved discussions (waiting on @naorlevi, @randmaayan, and @udilevin)

___
*[`android/pnddocs/native-android.md` line 11 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0jhR8v-l-2rghZhV-4:-O0jhR8v-l-2rghZhV-5:b-fygc8l) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/929fde942ee058001576ae0e3beae9e7c62cd270/android/pnddocs/native-android.md#L11)):*
> ```Markdown
> >- Retroactive Page View analytics and page view activated guides. 
> >- Code-based tooltips
> > The rest is supported by our track events only solution. We plan to add codeless support in the future.
> ```

You are missing an additional new line here or a new bullet. The last sentence is awkwardly continuing the second bullet
___
*[`android/pnddocs/jetpack_compose-android.md` line 6 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0jhrWcBZQ9hOA6SpyI:-O0jhrWcBZQ9hOA6SpyJ:btg1v44) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/929fde942ee058001576ae0e3beae9e7c62cd270/android/pnddocs/jetpack_compose-android.md#L6)):*
> ```Markdown
> >Starting **SDK 3.3**, Pendo support for Jetpack Compose includes the following:
> >- Retroactive Page View analytics and page view activated guides. 
> >- Code-based tooltips
> ```

Missing '.' at the end of the line. I would add a anchor link to the section below with the pendoModifier (see step 4 comment example if you're not sure what I mean)


<!-- Sent from Reviewable.io -->

2024-07-01 21:22 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: 2 of 4 files reviewed, 10 unresolved discussions (waiting on @naorlevi, @randmaayan, and @udilevin)

___
*[`android/pnddocs/jetpack_compose-android.md` line 64 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0k9v-T9r8eUBryQ_85:-O0k9v-T9r8eUBryQ_86:b-dgggg1) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/929fde942ee058001576ae0e3beae9e7c62cd270/android/pnddocs/jetpack_compose-android.md#L64)):*
> ```Markdown
> 
> ```kotlin
> val navController = rememberNavController()
> ```

do we have better name than navController? (we later pass in navController.navController)
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 2 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iJCqe-2htSBhMERJw:-O0kAFDx4ln-O8nBKCW7:btitd17) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L2)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

I would change the alert from IMPORTANT to WARNING. That's my opinion but maybe worth getting a crowd vote on this
</blockquote></details>

I take it back, IMPORTANT is probably better. Closing


<!-- Sent from Reviewable.io -->

2024-07-01 21:36 UTC, noambartouv requested changes
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: 2 of 4 files reviewed, 11 unresolved discussions (waiting on @naorlevi, @randmaayan, and @udilevin)

___
*[`android/pnddocs/native-android.md` line 7 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iHyr74Q84LGQnDWcb:-O0kAp9g1UoppGzm6hC8:byfvl3m) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/native-android.md#L7)):*
<details><summary><i>Previously, randmaayan wrote…</i></summary><blockquote>

1. please take a look. 
2. done.
</blockquote></details>

Where does it beta? I would add it to the beginning "Jetpack Compose (Beta)"
I suggest to to phrase:
"**Jetpack Compose (Beta)**, is available as of SDK 3.3. Support includes:
___
*[`android/pnddocs/native-android.md` line 11 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0kBfXwCMfpEzooA4_R:-O0kBfXwCMfpEzooA4_S:b76qy82) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/929fde942ee058001576ae0e3beae9e7c62cd270/android/pnddocs/native-android.md#L11)):*
> ```Markdown
> >- Retroactive Page View analytics and page view activated guides. 
> >- Code-based tooltips
> > The rest is supported by our track events only solution. We plan to add codeless support in the future.
> ```

Alternative phrasing suggestion:
"Additional codeless support is expected in future releases. At the moment, click analytics and click triggers for guides are not available, please use track events in such scenarios."


<!-- Sent from Reviewable.io -->

2024-07-02 13:36 UTC, randmaayan reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @naorlevi, @noambartouv, and @udilevin)

___
*[`android/pnddocs/native-android.md` line 7 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iHyr74Q84LGQnDWcb:-O0lx5KU-ZBFzz2g3PDV:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/native-android.md#L7)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Where does it beta? I would add it to the beginning "Jetpack Compose (Beta)"
I suggest to to phrase:
"**Jetpack Compose (Beta)**, is available as of SDK 3.3. Support includes:
</blockquote></details>

Done.
___
*[`android/pnddocs/jetpack_compose-android.md` line 6 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0jhrWcBZQ9hOA6SpyI:-O0lyQzG6HrT1blmj0KE:b-1vyo32) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/929fde942ee058001576ae0e3beae9e7c62cd270/android/pnddocs/jetpack_compose-android.md#L6)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Missing '.' at the end of the line. I would add a anchor link to the section below with the pendoModifier (see step 4 comment example if you're not sure what I mean)
</blockquote></details>

take a look
___
*[`android/pnddocs/jetpack_compose-android.md` line 54 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0jh-rv1cv4ABtQqRTp:-O0lxnwm3k7n0j-d4sLs:b-ltijsi) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/929fde942ee058001576ae0e3beae9e7c62cd270/android/pnddocs/jetpack_compose-android.md#L54)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

I think this step should be before pendoTag - I would swap steps 2 and 3
</blockquote></details>

pendoTag is a must. 
step 3 is only if you're using jetpack navigation.
___
*[`android/pnddocs/jetpack_compose-android.md` line 64 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0k9v-T9r8eUBryQ_85:-O0lxZy-6TVzuwo1ha4L:b-too1yd) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/929fde942ee058001576ae0e3beae9e7c62cd270/android/pnddocs/jetpack_compose-android.md#L64)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

do we have better name than navController? (we later pass in navController.navController)
</blockquote></details>

changed to navHostController.
___
*[`android/pnddocs/jetpackCompose_instructions.md` line 1 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0iJg-Q1ENWzYXCUhpT:-O0lyY4yBiJ6AS7NXJSL:b18gacy) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/696a7b712fa5ab0db74104b1b33e6d0157eb154f/android/pnddocs/jetpackCompose_instructions.md#L1)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Navigating to this article via a small link in the android native instructions will lead to a big drop off rate. If this is truly open beta and we want people to interact with it then we need to make it as visible as possible and place it where the users expect it (could be more than one place) - in our github that is clearly the main page with all the other installation instructions and perhaps you are right we should also link from the view based instructions (but this is secondary). You will have a big drop off of users reaching it by placing it as a small link in an alert inside the android native article.

By moving it to the main, though, we need to make sure everything remains clear. I think we will introduce an issue regarding view-based vs JPC beta, and it will also raise confusion around iOS since UIKit and SwiftUI aren't mentioned while JPC will be. We need to address those issues - we can brainstorm on this together to think of solutions
</blockquote></details>

ack, lets talk.


<!-- Sent from Reviewable.io -->

2024-07-02 14:39 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @naorlevi, @randmaayan, and @udilevin)

___
*[`android/pnddocs/native-android.md` line 137 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0nqR4272aKSuEE5fyX:-O0nqR4272aKSuEE5fyY:bp9xb0x) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/7e51d3e97c24cb9175140c2751ef74c2c95c720a/android/pnddocs/native-android.md#L137)):*
> ```Markdown
>         </intent-filter>
>     </activity>
> ```

I suggest to add an optional step here (so step #4 and after increment the existing steps below):

" ## Step 4. (Optional - for Jetpack Compose Beta integration only) continue to the beta installation instructions and complete the additional steps" (add a link to the instructions, maybe even straight to step 2 in those instructions)   
___
*[`android/pnddocs/jetpack_compose-android.md` line 6 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0jhrWcBZQ9hOA6SpyI:-O0nsGBnAQVF2Ia3KOEi:bf8gb8b) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/929fde942ee058001576ae0e3beae9e7c62cd270/android/pnddocs/jetpack_compose-android.md#L6)):*
<details><summary><i>Previously, randmaayan wrote…</i></summary><blockquote>

take a look
</blockquote></details>

Formating looks good.
Capital letter missing and I suggest to replace with "Additional info"
___
*[`android/pnddocs/jetpack_compose-android.md` line 54 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0jh-rv1cv4ABtQqRTp:-O0no1zfApQ0T2XC0Ebk:bra7sfb) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/929fde942ee058001576ae0e3beae9e7c62cd270/android/pnddocs/jetpack_compose-android.md#L54)):*
<details><summary><i>Previously, randmaayan wrote…</i></summary><blockquote>

pendoTag is a must. 
step 3 is only if you're using jetpack navigation.
</blockquote></details>

pendoTag is not a must. I can utilize the beta just for page analytics, and page view guides for pages using jetpack navigation which is its own value, and I believe is of more value to our customers than the code-based tooltips (after the feedback prospects shared with us). 

Regardless
Step 1 is integration (happens once)
Step 2 is integration (happens once)
Step 3 is API command on a need basis (will change over time and be added in additional places in the code in the future)
Step 4 is more integration (happens once)

All the things that only need to happen once when first integrating should come before API calls that will be change/added on a need basis
___
*[`android/pnddocs/jetpack_compose-android.md` line 59 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0nruc1CaDG8h21f8vQ:-O0nruc1CaDG8h21f8vR:bd7n68i) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/7e51d3e97c24cb9175140c2751ef74c2c95c720a/android/pnddocs/jetpack_compose-android.md#L59)):*
> ```Markdown
> 
> 
> - Without this step, Pendo will not be able to recognize Compose pages in your app.
> ```

Turn the sentence into a requirement, rather than an issue. 
"This step is required for the SDK to recognize Compose pages in your app."


<!-- Sent from Reviewable.io -->

2024-07-02 14:42 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @naorlevi, @randmaayan, and @udilevin)

___
*[`android/pnddocs/native-android.md` line 137 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0nqR4272aKSuEE5fyX:-O0nstQ7C8IJcgFgYhGX:b-at037v) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/7e51d3e97c24cb9175140c2751ef74c2c95c720a/android/pnddocs/native-android.md#L137)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

I suggest to add an optional step here (so step #4 and after increment the existing steps below):

" ## Step 4. (Optional - for Jetpack Compose Beta integration only) continue to the beta installation instructions and complete the additional steps" (add a link to the instructions, maybe even straight to step 2 in those instructions)
</blockquote></details>

Didn't expect github to translate that into a link to some issue 🤯
basically suggested to an optional step 4 and increment the existing steps thereafter 


<!-- Sent from Reviewable.io -->

2024-07-02 14:45 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @naorlevi, @randmaayan, and @udilevin)

___
*[`android/pnddocs/jetpack_compose-android.md` line 1 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0ntTTvCYhyOBcTvt1m:-O0ntTTvCYhyOBcTvt1n:b6pbd64) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/7e51d3e97c24cb9175140c2751ef74c2c95c720a/android/pnddocs/jetpack_compose-android.md#L1)):*
> ```Markdown
> # Jetpack Compose (Beta)
> ```

Let's check with Naor/Anat if perhaps we want to request feedback around jetpack compose via the article.
If so do we push them to open a ticket / discussion thread in the github or do they want to collect that info in another way. Also what scope of information - is it limited to integration / technical questions or general jpc feedback

FYI @naorlevi 


<!-- Sent from Reviewable.io -->

2024-07-03 11:52 UTC, randmaayan reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @naorlevi, @noambartouv, and @udilevin)

___
*[`android/pnddocs/native-android.md` line 137 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0nqR4272aKSuEE5fyX:-O0sMK5x-06a3wwlsL_3:b-66tx42) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/7e51d3e97c24cb9175140c2751ef74c2c95c720a/android/pnddocs/native-android.md#L137)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Didn't expect github to translate that into a link to some issue 🤯
basically suggested to an optional step 4 and increment the existing steps thereafter
</blockquote></details>

done. take a look
___
*[`android/pnddocs/jetpack_compose-android.md` line 54 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0jh-rv1cv4ABtQqRTp:-O0sKLrW13A_4TpDcSRT:b1z8ow3) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/929fde942ee058001576ae0e3beae9e7c62cd270/android/pnddocs/jetpack_compose-android.md#L54)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

pendoTag is not a must. I can utilize the beta just for page analytics, and page view guides for pages using jetpack navigation which is its own value, and I believe is of more value to our customers than the code-based tooltips (after the feedback prospects shared with us). 

Regardless
Step 1 is integration (happens once)
Step 2 is integration (happens once)
Step 3 is API command on a need basis (will change over time and be added in additional places in the code in the future)
Step 4 is more integration (happens once)

All the things that only need to happen once when first integrating should come before API calls that will be change/added on a need basis
</blockquote></details>

Okay, fixed. resolved. 
___
*[`android/pnddocs/jetpack_compose-android.md` line 59 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0nruc1CaDG8h21f8vQ:-O0sKzIeCPn6ues09bG3:bk7dv1q) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/7e51d3e97c24cb9175140c2751ef74c2c95c720a/android/pnddocs/jetpack_compose-android.md#L59)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Turn the sentence into a requirement, rather than an issue. 
"This step is required for the SDK to recognize Compose pages in your app."
</blockquote></details>

good one. done. 


<!-- Sent from Reviewable.io -->

2024-07-03 11:58 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @naorlevi, @randmaayan, and @udilevin)

___
*[`android/pnddocs/jetpack_compose-android.md` line 1 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0ntTTvCYhyOBcTvt1m:-O0sRWe98o-OqnwEMqe5:b8hhcy) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/7e51d3e97c24cb9175140c2751ef74c2c95c720a/android/pnddocs/jetpack_compose-android.md#L1)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Let's check with Naor/Anat if perhaps we want to request feedback around jetpack compose via the article.
If so do we push them to open a ticket / discussion thread in the github or do they want to collect that info in another way. Also what scope of information - is it limited to integration / technical questions or general jpc feedback

FYI @naorlevi
</blockquote></details>

We can add this later as well


<!-- Sent from Reviewable.io -->

2024-07-03 13:30 UTC, noambartouv approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @randmaayan)



<!-- Sent from Reviewable.io -->

2024-07-04 08:24 UTC, DavidPendo commented
*[`README.md` line 67 at r6](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0wpLrf5OlnxXJxZHE9:-O0wpLrf5OlnxXJxZHEA:bccxlqb) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/65c2ef70e0231b4ce8e75767094abf0c9e3b0079/README.md#L67)):*
> ```Markdown
> 
> - For technical issues, [review open issues](https://github.com/pendo-io/pendo-mobile-sdk/issues) or [submit a new issue](https://github.com/pendo-io/pendo-mobile-sdk/issues).
> - For Dev issues with Android applications, refer to this [resource](https://developer.android.com/studio/build/multidex).
> ```

It should be **Dex**... and is this relevant to jpc apps at all, if your `minSdkVersion` is 21 or higher, multidex is enabled by default and you don't need the multidex library.


<!-- Sent from Reviewable.io -->

2024-07-04 08:26 UTC, DavidPendo commented
*[`android/pnddocs/android_sdk_manual_installation.md` line 34 at r6](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0wqNUVDFtynsSwuPv9:-O0wqNUVDFtynsSwuPvA:b-ya81ng) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/65c2ef70e0231b4ce8e75767094abf0c9e3b0079/android/pnddocs/android_sdk_manual_installation.md#L34)):*
> ```Markdown
> - For technical issues, please [review open issues](https://github.com/pendo-io/pendo-mobile-sdk/issues) or [submit a new issue](https://github.com/pendo-io/pendo-mobile-sdk/issues).
> - Release notes can be found [here](https://developers.pendo.io/category/mobile-sdk/).
> - For Dev issues with Android applications, refer to this [resource](https://developer.android.com/studio/build/multidex).
> ```

Same as above


<!-- Sent from Reviewable.io -->

2024-07-04 08:28 UTC, DavidPendo commented
*[`android/pnddocs/jetpack_compose-android.md` line 89 at r6](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149#-O0wqyBs8HWNp4oCSPYC:-O0wqyBs8HWNp4oCSPYD:b-ya81ng) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/65c2ef70e0231b4ce8e75767094abf0c9e3b0079/android/pnddocs/jetpack_compose-android.md#L89)):*
> ```Markdown
> - For technical issues, please [review open issues](https://github.com/pendo-io/pendo-mobile-sdk/issues) or [submit a new issue](https://github.com/pendo-io/pendo-mobile-sdk/issues).
> - Release notes can be found [here](https://developers.pendo.io/category/mobile-sdk/).
> - For Dev issues with Android applications, refer to this [resource](https://developer.android.com/studio/build/multidex).
> ```

Same as above


<!-- Sent from Reviewable.io -->

2024-07-04 08:29 UTC, DavidPendo approved these changes
> Reviewed 1 of 4 files at r1, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: all files reviewed, 3 unresolved discussions (waiting on @randmaayan)



<!-- Sent from Reviewable.io -->

2024-07-04 08:31 UTC, DavidPendo approved these changes
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)* status: all files reviewed, 3 unresolved discussions (waiting on @randmaayan)



<!-- Sent from Reviewable.io -->

2024-07-04 08:43 UTC, DavidPendo commented
[merge]





<!-- Sent from Reviewable.io -->

2024-07-04 08:43 UTC, merged

2024-07-04 08:43 UTC, pendo-ops commented
All JIRA issue transitioned/labeled.
* [APP-99856](https://pendo-io.atlassian.net/browse/APP-99856): Jira Issue APP-99856: Changed to Resolved


Branch APP-99856_install_instructions_jpc deleted