APP-104740_flutter_codeless_docs
pendo-io/pendo-mobile-sdk pull request #157
Opened 2024-07-22 13:56 UTC by MikePendo

2024-07-22 22:02 UTC, naorlevi requested changes
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @DavidPendo, @MaximShnirman, @MikePendo, @noambartouv, and @udilevin)

___
*[`android/pnddocs/flutter-android.md` line 4 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2RSqxOEHqqLMt9jcu5:-O2RSqxOEHqqLMt9jcu6:b-olssqs) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/0f59d18e73e5c11c65872c4a508c29861b12971a/android/pnddocs/flutter-android.md#L4)):*
> ```Markdown
> 
> >[!IMPORTANT]
> >Flutter codeless solution is currently in OPEN BETA
> ```

low-code instead of codeless
___
*[`ios/pnddocs/flutter-ios.md` line 4 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2RSWkU0njy47Qif2qb:-O2RSWkU0njy47Qif2qc:b-2c4jjv) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/0f59d18e73e5c11c65872c4a508c29861b12971a/ios/pnddocs/flutter-ios.md#L4)):*
> ```Markdown
> 
> >[!IMPORTANT]
> >Flutter codeless solution is currently in OPEN BETA
> ```

Flutter low-code solution is currently in OPEN BETA
___
*[`other/flutter-notes-known-issues-limitations.md` line 4 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2RRxSV8VnCm_UgDp3u:-O2RRxSV8VnCm_UgDp3v:b-eprgxb) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/0f59d18e73e5c11c65872c4a508c29861b12971a/other/flutter-notes-known-issues-limitations.md#L4)):*
> ```Markdown
> 
> ## Navigation Libraries
> Currently, the page recognition solution supports the standard Flutter Navigator and GoRouter libraries. Integration with additional navigation frameworks is planned for future releases.
> ```

Remove "Currently" from the beginning
___
*[`other/flutter-notes-known-issues-limitations.md` line 7 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2RRoeL1yIvdeSDWfeF:-O2RRoeMDj4CMsqQuKtb:b-xwmy90) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/0f59d18e73e5c11c65872c4a508c29861b12971a/other/flutter-notes-known-issues-limitations.md#L7)):*
> ```Markdown
> When using GoRouter with nested routes, ensure each branch includes a PendoNavigationObserver() to accurately track route changes and enable proper element detection.
> 
> ## Clickable Elemnts
> ```

Elements
___
*[`other/flutter-notes-known-issues-limitations.md` line 8 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2RS5NxCmfrkeIaJIme:-O2RS5NxCmfrkeIaJImf:b-9ta4ur) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/0f59d18e73e5c11c65872c4a508c29861b12971a/other/flutter-notes-known-issues-limitations.md#L8)):*
> ```Markdown
> 
> ## Clickable Elemnts
> The current implementation supports basic touch interactions (down and up) on a range of standard Flutter widgets, including:
> ```

touchDown and touchUp
___
*[`other/flutter-notes-known-issues-limitations.md` line 13 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2RSAc_DXGxCt-fmOUh:-O2RSAc_DXGxCt-fmOUi:b1uekgu) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/0f59d18e73e5c11c65872c4a508c29861b12971a/other/flutter-notes-known-issues-limitations.md#L13)):*
> ```Markdown
> PopupMenuButton, DropdownButton, Checkbox, Chip, ChoiceChip, FilterChip, InputChip, Switch, Radio, ListTile
> TabBar, BottomNavigationBar, SelectableText, TextField
> Support for more complex interaction types (e.g. drag, swiped) is planned for future releases.
> ```

e.g Drag and Swipe gestures


<!-- Sent from Reviewable.io -->

2024-07-22 22:37 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 4 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2RSqxOEHqqLMt9jcu5:-O2Ra--P3njZ0y_hpe5W:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/0f59d18e73e5c11c65872c4a508c29861b12971a/android/pnddocs/flutter-android.md#L4)):*
<details><summary><i>Previously, naorlevi (pippoTLV) wrote…</i></summary><blockquote>

low-code instead of codeless
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-22 22:37 UTC, MikePendo commented
*[`ios/pnddocs/flutter-ios.md` line 4 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2RSWkU0njy47Qif2qb:-O2Ra-rc3HbJs7r2x_5p:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/0f59d18e73e5c11c65872c4a508c29861b12971a/ios/pnddocs/flutter-ios.md#L4)):*
<details><summary><i>Previously, naorlevi (pippoTLV) wrote…</i></summary><blockquote>

Flutter low-code solution is currently in OPEN BETA
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-22 22:38 UTC, MikePendo commented
*[`other/flutter-notes-known-issues-limitations.md` line 7 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2RRoeL1yIvdeSDWfeF:-O2RaAbT-bBCdYNdyP40:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/0f59d18e73e5c11c65872c4a508c29861b12971a/other/flutter-notes-known-issues-limitations.md#L7)):*
<details><summary><i>Previously, naorlevi (pippoTLV) wrote…</i></summary><blockquote>

Elements
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-22 22:39 UTC, MikePendo commented
*[`other/flutter-notes-known-issues-limitations.md` line 8 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2RS5NxCmfrkeIaJIme:-O2RaGiODGBaUqgiagad:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/0f59d18e73e5c11c65872c4a508c29861b12971a/other/flutter-notes-known-issues-limitations.md#L8)):*
<details><summary><i>Previously, naorlevi (pippoTLV) wrote…</i></summary><blockquote>

touchDown and touchUp
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-22 22:39 UTC, MikePendo commented
*[`other/flutter-notes-known-issues-limitations.md` line 13 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2RSAc_DXGxCt-fmOUh:-O2RaUNKDtxgkdLZGica:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/0f59d18e73e5c11c65872c4a508c29861b12971a/other/flutter-notes-known-issues-limitations.md#L13)):*
<details><summary><i>Previously, naorlevi (pippoTLV) wrote…</i></summary><blockquote>

e.g Drag and Swipe gestures
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-23 03:34 UTC, udilevin reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @DavidPendo, @MaximShnirman, @MikePendo, @naorlevi, and @noambartouv)

___
*[`other/flutter-notes-known-issues-limitations.md` line 7 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2RRoeL1yIvdeSDWfeF:-O2SdUqi4xBibx8FdvO3:bt6ovgm) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/0f59d18e73e5c11c65872c4a508c29861b12971a/other/flutter-notes-known-issues-limitations.md#L7)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

what are elements in Pendo? Should probably be features 


<!-- Sent from Reviewable.io -->

2024-07-23 04:42 UTC, naorlevi commented
*[`other/flutter-notes-known-issues-limitations.md` line 7 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2RRoeL1yIvdeSDWfeF:-O2StRkf1bHAnt9xd_3B:ba2b9mk) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/0f59d18e73e5c11c65872c4a508c29861b12971a/other/flutter-notes-known-issues-limitations.md#L7)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

what are elements in Pendo? Should probably be features
</blockquote></details>

perhaps Widgets?


<!-- Sent from Reviewable.io -->

2024-07-23 04:43 UTC, naorlevi reviewed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 1 unresolved discussion (waiting on @DavidPendo, @MaximShnirman, @noambartouv, and @udilevin)



<!-- Sent from Reviewable.io -->

2024-07-23 06:20 UTC, MaximShnirman commented
*[`other/flutter-notes-known-issues-limitations.md` line 3 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TES-W7eXIufUvTODU:-O2TES-W7eXIufUvTODV:b-7gad7y) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/other/flutter-notes-known-issues-limitations.md#L3)):*
> ```Markdown
> 
> 
> ## Navigation Libraries
> ```

I think we should have a dedicated place to put the native flutter integration in, like the calls to set up, start sessions, etc.
under that, id expect to have more framework specific integration


<!-- Sent from Reviewable.io -->

2024-07-23 06:28 UTC, MaximShnirman commented
*[`other/flutter-notes-known-issues-limitations.md` line 2 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TEtdTDYs6J5qTKjD7:-O2TEtdTDYs6J5qTKjD8:b-v5l20j) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/other/flutter-notes-known-issues-limitations.md#L2)):*
> ```Markdown
> 
> ```

we are missing go router nested branching integration (shell support) 

1. need to add PendoNavigationObserver in each branch
2. need to add PendoNavigationObserver under the go router config 
3. need to create a 'static NestedBranchesObserver nestedBranchesObserver = NestedBranchesObserver();' 
4. under the build method call it like so 'nestedBranchesObserver.addListener(_router);' (where _router is the GoRouter one)
5. in case this was added to a stateful widget, call the following: 'pendoNestedBranchesObserver.removeListener(_router);' under the dispose method

example can be found in our host app, under: 'shell_route_navigation.dart' file
and also documentation of this is here: https://pendo-io.atlassian.net/browse/APP-100887


<!-- Sent from Reviewable.io -->

2024-07-23 06:29 UTC, MaximShnirman reviewed
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 7 unresolved discussions (waiting on @DavidPendo, @MikePendo, @noambartouv, and @udilevin)

___
*[`android/pnddocs/flutter-android.md` line 36 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TDGeD4ZBuA4Sg8NGe:-O2TCi8R4-G-9Fa4jXci:bi1qbsv) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L36)):*
> ```Markdown
>     ```java
>     android {
>         minSdkVersion 21
> ```

@DavidPendo was this changed? 
___
*[`android/pnddocs/flutter-android.md` line 59 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TDhx6DFkHFWb6JVkj:-O2TDhx6DFkHFWb6JVkk:bg48c30) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L59)):*
> ```Markdown
> `-optimizations *other optimizations*,!code/allocation/variable`
> 
> ## Step 2. Pendo SDK integration
> ```

why is this step part of the specific Android integration? 
___
*[`android/pnddocs/flutter-android.md` line 95 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TDRqA2SfCBHYEofep:-O2TDRqA2SfCBHYEofeq:baojplj) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L95)):*
> ```Markdown
> 
> 
> 3. Add Navigation Observers <br>
> ```

i think we should include the import part as well for this
___
*[`ios/pnddocs/flutter-ios.md` line 14 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TDz3941H_N-IPKczl:-O2TDz3941H_N-IPKczm:bh11ttq) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/ios/pnddocs/flutter-ios.md#L14)):*
> ```Markdown
> In the root folder of your flutter app add the Pendo package: `flutter pub add pendo_sdk`.
> 
> ## Step 2. Integration
> ```

same, im not sure why we got flutter specific integration in ios and in android 


<!-- Sent from Reviewable.io -->

2024-07-23 06:30 UTC, MaximShnirman reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 7 unresolved discussions (waiting on @DavidPendo, @MikePendo, @noambartouv, and @udilevin)



<!-- Sent from Reviewable.io -->

2024-07-23 06:30 UTC, MaximShnirman requested changes
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 7 unresolved discussions (waiting on @DavidPendo, @MikePendo, @noambartouv, and @udilevin)



<!-- Sent from Reviewable.io -->

2024-07-23 08:07 UTC, DavidPendo commented
*[`android/pnddocs/flutter-android.md` line 36 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TDGeD4ZBuA4Sg8NGe:-O2TaZw44cFX8WEfDPqU:b-c7meig) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L36)):*
<details><summary><i>Previously, MaximShnirman (Maxim Shnirman) wrote…</i></summary><blockquote>

@DavidPendo was this changed?
</blockquote></details>

No... The most important here is **minSdkVersion**, meaning the hosting app can't have the lowest version that Pendo requires.

The **compileSdkVersion** is irrelevant here because it is about the Android API you can access during development. So I would remove it @MikePendo 


<!-- Sent from Reviewable.io -->

2024-07-23 08:20 UTC, DavidPendo approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 8 unresolved discussions (waiting on @MikePendo, @noambartouv, and @udilevin)



<!-- Sent from Reviewable.io -->

2024-07-23 08:46 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 26 unresolved discussions (waiting on @MaximShnirman, @MikePendo, and @udilevin)

___
*[`android/pnddocs/flutter-android.md` line 8 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TXlmG9hjrwE2MTCy5:-O2TXlmG9hjrwE2MTCy6:bki3hg) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L8)):*
> ```Markdown
> >[!IMPORTANT]
> >Requirements:
> >- Flutter: ">=3.3.0"
> ```

the >= an < symbols are confusing. Please use words and remove the quotes (styling should remain consistent across the entire github)
___
*[`android/pnddocs/flutter-android.md` line 9 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TXc988Cp8LhIBnrpu:-O2TXc999LEgWG15LtSD:b-swdw3) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L9)):*
> ```Markdown
> >Requirements:
> >- Flutter: ">=3.3.0"
> >- SDK: ">=2.18.0 < 4.0.0" 
> ```

what does 'SDK' mean? Is there no dart requirement anymore?
___
*[`android/pnddocs/flutter-android.md` line 27 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2T_Fl18CU27adXl0Sd:-O2T_Fl18CU27adXl0Se:bqv23jr) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L27)):*
> ```Markdown
>             url "https://software.mobile.pendo.io/artifactory/androidx-release"
>         }
>     mavenCentral()
> ```

missing indent for mavenCentral()
___
*[`android/pnddocs/flutter-android.md` line 64 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TY4JXCvPlnHeZbJu-:-O2TY4JXCvPlnHeZbJu0:b-jpquxo) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L64)):*
> ```Markdown
> >The `API Key` can be found in your Pendo Subscription Settings in App Details.
> 
> 1. Add the following code in the `initState` method:
> ```

1. this is a change from existing customers - will existing customers upgrading encounter issues because setup is expected in a different location now?
2. Do we need to mention in which file the initState method can be found? Is it obvious to all flutter devs?
___
*[`android/pnddocs/flutter-android.md` line 95 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TDRqA2SfCBHYEofep:-O2TZBTm3cX_tz4MajK9:b32v57) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L95)):*
<details><summary><i>Previously, MaximShnirman (Maxim Shnirman) wrote…</i></summary><blockquote>

i think we should include the import part as well for this
</blockquote></details>

+1
___
*[`android/pnddocs/flutter-android.md` line 95 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2Ta7pMDu0dXsXYldl7:-O2Ta7pN-0ezG9vltJux:b-vy1zl6) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L95)):*
> ```Markdown
> 
> 
> 3. Add Navigation Observers <br>
> ```

Let's combine the two lines before the code block. It looks weird as 1 line
___
*[`android/pnddocs/flutter-android.md` line 98 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2Tb_dO2oh8pz0j_Dzo:-O2Tb_dO2oh8pz0j_Dzp:bomcyg8) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L98)):*
> ```Markdown
> Add PendoNavigationObserver for each app Navigator
>     ```dart
>     // For main Navigator in MaterialApp/CupertinoApp 
> ```

Alternative text:
Observes the MaterialApp/CupertinoApp main Navigator 
___
*[`android/pnddocs/flutter-android.md` line 105 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2Tc6fo4x6m3RL140BA:-O2Tc6fo4x6m3RL140BB:b283vha) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L105)):*
> ```Markdown
>         ],); 
> 
>     // For Navigator widget
> ```

Alternative text:
Observes the widget Navigator
___
*[`android/pnddocs/flutter-android.md` line 112 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TcBkYBNk4z_upoQKL:-O2TcBkZ2pvJDbUoyTSr:b-muoiat) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L112)):*
> ```Markdown
>         ],);
>         
>     // For Routes API with GoRouter 3d party
> ```

Alternative text:
Observes the GoRouter 3rd party routing 
___
*[`android/pnddocs/flutter-android.md` line 121 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TaM71DJ-TlDvatdji:-O2TaM71DJ-TlDvatdjj:bo620w1) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L121)):*
> ```Markdown
> 
>     ```
> 4. Add clicks listener<br>
> ```

Let's combine the two lines before the code block. It looks weird as 1 line

typo: Add a click listener / add click listeners
___
*[`android/pnddocs/flutter-android.md` line 122 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TakIU8BEf3ujiplqe:-O2TakIU8BEf3ujiplqf:bxbxj68) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L122)):*
> ```Markdown
>     ```
> 4. Add clicks listener<br>
> At the root of the project, wrap the main widget with PendoActionListener:
> ```

Alternative:
Wrap the main widget with a PendoActionListener in the root of the project.
___
*[`android/pnddocs/flutter-android.md` line 125 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TcncbC9E1F9LEBjNW:-O2TcncbC9E1F9LEBjNX:blxrbmx) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L125)):*
> ```Markdown
>     ```dart
>     Widget build(BuildContext context) {
>     return PendoActionListener( // Use PendoActionListener to track action clicks 
> ```

typo: Use the
___
*[`android/pnddocs/flutter-android.md` line 140 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TdiuQ84yhyiKlbfNM:-O2TdiuQ84yhyiKlbfNN:b-15aetg) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L140)):*
> ```Markdown
> 
> >[!TIP]
> >In some cases you may find Track Events useful to capture specific analytics events.
> ```

This looks weird as a tip and after it a code block. In general I don't see we suggest track events in other integrations. I suggest to move its own Optional step if we want to keep it.


Alternative text:
Use track events to programmatically notify Pendo of custom events of interest:

Link:
let's link 'track events' to the resource center article: https://support.pendo.io/hc/en-us/articles/360032294151-Track-Events
___
*[`android/pnddocs/flutter-android.md` line 179 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TgBrO0Wq0S5hC5Izw:-O2TgBrO0Wq0S5hC5Izx:bdvzsv2) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L179)):*
> ```Markdown
> 
> ## Limitations
> - [Notes, Known Issues & Limitations](/other/flutter-notes-known-issues-limitations.md).
> ```

Alternative text:
Flutter Open Beta support and know issues 
___
*[`ios/pnddocs/flutter-ios.md` line 14 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TDz3941H_N-IPKczl:-O2TgWpb-cHCxoK9fl_7:b-vo7bw1) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/ios/pnddocs/flutter-ios.md#L14) [...]

2024-07-23 08:48 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 27 unresolved discussions (waiting on @MaximShnirman, @MikePendo, and @udilevin)

*[a discussion](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TlbfAC98aOfCPfKFw:-O2TlbfAC98aOfCPfKFx:b-rzn9wl) (no related file):*
Do we need to update anything in the flutter API docs? The setup method?
https://github.com/pendo-io/pendo-mobile-sdk/blob/APP-104740_flutter_codeless_docs/api-documentation/flutter-apis.md

___


<!-- Sent from Reviewable.io -->

2024-07-23 08:49 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 27 unresolved discussions (waiting on @MaximShnirman, @MikePendo, and @udilevin)

*[a discussion](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2Tlr7R07J_j1ndN6Pe:-O2Tlr7R07J_j1ndN6Pf:b-h91v5c) (no related file):*
Did we review the flutter api docs? Anything we need to add / change?

https://github.com/pendo-io/pendo-mobile-sdk/blob/APP-104740_flutter_codeless_docs/api-documentation/flutter-apis.md

___


<!-- Sent from Reviewable.io -->

2024-07-23 13:34 UTC, MikePendo commented
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Do we need to update anything in the flutter API docs? The setup method?
https://github.com/pendo-io/pendo-mobile-sdk/blob/APP-104740_flutter_codeless_docs/api-documentation/flutter-apis.md
</blockquote></details>

I think no, I would like to consider classes as PendoObservebale and ActionListener NOT as new API 




<!-- Sent from Reviewable.io -->

2024-07-23 13:39 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 8 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TXlmG9hjrwE2MTCy5:-O2UnFOI0qkqMWSTkkYk:b-i86335) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L8)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

the >= an < symbols are confusing. Please use words and remove the quotes (styling should remain consistent across the entire github)
</blockquote></details>

That's how flutter use it and that is what written in the pubspec yaml and I believe should be easy to read for flutter devs. looking at the other repos I dont see them mention it at all @naorlevi your call


<!-- Sent from Reviewable.io -->

2024-07-23 13:39 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 9 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TXc988Cp8LhIBnrpu:-O2UoNAU8Yydn2jaXyaN:baxbh7v) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L9)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

what does 'SDK' mean? Is there no dart requirement anymore?
</blockquote></details>

Dart come together with the SDK. (in most cases )


<!-- Sent from Reviewable.io -->

2024-07-23 13:41 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 36 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TDGeD4ZBuA4Sg8NGe:-O2Uol_94-TXXbyLjlTt:b-hfpv0l) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L36)):*
<details><summary><i>Previously, DavidPendo wrote…</i></summary><blockquote>

Or you can leave it as it does not affect anything
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2024-07-23 13:42 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 59 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TDhx6DFkHFWb6JVkj:-O2Uosr57e-VO0WVF_Us:b-wyagfv) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L59)):*
<details><summary><i>Previously, MaximShnirman (Maxim Shnirman) wrote…</i></summary><blockquote>

why is this step part of the specific Android integration?
</blockquote></details>

@DavidPendo maybe you can answer (I took it from the last Flutter integration)


<!-- Sent from Reviewable.io -->

2024-07-23 13:52 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 64 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TY4JXCvPlnHeZbJu-:-O2UrAyK84s7nJ2HwEjG:b-v9mrbv) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L64)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

1. this is a change from existing customers - will existing customers upgrading encounter issues because setup is expected in a different location now?
2. Do we need to mention in which file the initState method can be found? Is it obvious to all flutter devs?
</blockquote></details>

1.
2. explained it in better words


<!-- Sent from Reviewable.io -->

2024-07-23 13:55 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 95 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TDRqA2SfCBHYEofep:-O2UrzmW85tyRxCWmTOE:b-piikje) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L95)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

+1
</blockquote></details>

added though dont think its necessary 


<!-- Sent from Reviewable.io -->

2024-07-23 13:57 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 98 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2Tb_dO2oh8pz0j_Dzo:-O2UsUMi0BOi07ECoXuR:b-n9tkhd) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L98)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Alternative text:
Observes the MaterialApp/CupertinoApp main Navigator
</blockquote></details>

changed


<!-- Sent from Reviewable.io -->

2024-07-23 13:59 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 105 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2Tc6fo4x6m3RL140BA:-O2Ut04fDn-PFlUneFyd:b-n9tkhd) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L105)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Alternative text:
Observes the widget Navigator
</blockquote></details>

changed


<!-- Sent from Reviewable.io -->

2024-07-23 13:59 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 112 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TcBkYBNk4z_upoQKL:-O2Ut1TW9aLFX-gzR5YZ:b499q7j) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L112)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Alternative text:
Observes the GoRouter 3rd party routing
</blockquote></details>

Changed


<!-- Sent from Reviewable.io -->

2024-07-23 14:10 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 140 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TdiuQ84yhyiKlbfNM:-O2UtlD1A_DX5jEUEpHy:b1xxd3b) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L140)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

This looks weird as a tip and after it a code block. In general I don't see we suggest track events in other integrations. I suggest to move its own Optional step if we want to keep it.


Alternative text:
Use track events to programmatically notify Pendo of custom events of interest:

Link:
let's link 'track events' to the resource center article: https://support.pendo.io/hc/en-us/articles/360032294151-Track-Events
</blockquote></details>

@naorlevi your call I think its fine @noambartouv added link


<!-- Sent from Reviewable.io -->

2024-07-23 14:11 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 179 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TgBrO0Wq0S5hC5Izw:-O2UvhJj2TSVgv2mhW7M:bs48qbk) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L179)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Alternative text:
Flutter Open Beta support and know issues
</blockquote></details>

I dont know @naorlevi 


<!-- Sent from Reviewable.io -->

2024-07-23 15:55 UTC, naorlevi commented
*[`android/pnddocs/flutter-android.md` line 8 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TXlmG9hjrwE2MTCy5:-O2VIQii6IW0u_YrzIxy:bfv30vk) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L8)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

That's how flutter use it and that is what written in the pubspec yaml and I believe should be easy to read for flutter devs. looking at the other repos I dont see them mention it at all @naorlevi your call
</blockquote></details>

That seems to be the standard then, leave it as is.


<!-- Sent from Reviewable.io -->

2024-07-23 15:59 UTC, naorlevi commented
*[`android/pnddocs/flutter-android.md` line 140 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TdiuQ84yhyiKlbfNM:-O2VJHF953yZBuLMNsQf:b-rxsub0) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L140)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

@naorlevi your call I think its fine @noambartouv added link
</blockquote></details>

ok. let's go with @noambartouv suggestion


<!-- Sent from Reviewable.io -->

2024-07-23 15:59 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 64 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TY4JXCvPlnHeZbJu-:-O2VJOXf59DUH-jY0sft:b-8ktna9) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L64)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

1.
2. explained it in better words
</blockquote></details>

1. No


<!-- Sent from Reviewable.io -->

2024-07-23 15:59 UTC, naorlevi commented
*[`android/pnddocs/flutter-android.md` line 179 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TgBrO0Wq0S5hC5Izw:-O2VJPW79DTQ0Sf1Anr3:bke8x54) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L179)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

I dont know @naorlevi
</blockquote></details>

No need in my opinion. We wrote it's beta before


<!-- Sent from Reviewable.io -->

2024-07-23 16:00 UTC, MikePendo commented
*[`other/flutter-notes-known-issues-limitations.md` line 9 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2ThD8JCxKzQrMipNUL:-O2VJVOX-GfRqww4kTv2:b7ovaac) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/other/flutter-notes-known-issues-limitations.md#L9)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

I think let's turn this into a list of widgets to a bullet list
</blockquote></details>

it becomes very long in that case 


<!-- Sent from Reviewable.io -->

2024-07-23 16:00 UTC, MikePendo commented
*[`other/flutter-notes-known-issues-limitations.md` line 8 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2Ti_3v438ppU78Ytjo:-O2VJfy8E-iHSjlwgmR0:b-swy3nu) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/other/flutter-notes-known-issues-limitations.md#L8)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Alternative text:
Our implementation supports ...
</blockquote></details>

changing though I dont see values in the change 


<!-- Sent from Reviewable.io -->

2024-07-23 16:01 UTC, MikePendo commented
*[`other/flutter-notes-known-issues-limitations.md` line 7 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2RRoeL1yIvdeSDWfeF:-O2VJl3R6q9QTbGiPsY3:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/0f59d18e73e5c11c65872c4a508c29861b12971a/other/flutter-notes-known-issues-limitations.md#L7)):*
<details><summary><i>Previously, naorlevi (pippoTLV) wrote…</i></summary><blockquote>

perhaps Widgets?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-23 16:27 UTC, MikePendo commented
*[`other/flutter-notes-known-issues-limitations.md` line 3 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TES-W7eXIufUvTODU:-O2VPfPa4WO4lbizyoxn:b-vze8x9) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/other/flutter-notes-known-issues-limitations.md#L3)):*
<details><summary><i>Previously, MaximShnirman (Maxim Shnirman) wrote…</i></summary><blockquote>

I think we should have a dedicated place to put the native flutter integration in, like the calls to set up, start sessions, etc.
under that, id expect to have more framework specific integration
</blockquote></details>

what? I am not sure I follow


<!-- Sent from Reviewable.io -->

2024-07-23 16:28 UTC, MikePendo commented
*[`other/flutter-notes-known-issues-limitations.md` line 16 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2Tiecd6gtrIGWx124K:-O2VQ0H1Eab2mtDDMWiu:b-i96st0) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/other/flutter-notes-known-issues-limitations.md#L16)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Let's remove the first sentence - it doesn't add anything.
</blockquote></details>

why? it gives more context about what the meaning of static vs dynamic?


<!-- Sent from Reviewable.io -->

2024-07-23 16:31 UTC, MikePendo commented
*[`other/flutter-notes-known-issues-limitations.md` line 13 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TiKxJ7331ijCJKyUG:-O2VQfQQ8wSyADZ-ZL4G:bb6un1j) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/other/flutter-notes-known-issues-limitations.md#L13)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Add a <br> at the end of the previous line (this sentence currently continues the previous line)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-07-23 16:48 UTC, MikePendo commented
*[`other/flutter-notes-known-issues-limitations.md` line 24 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TkYda6sV5M7y2IZdL:-O2VUW7yE76knIlHJM0h:b-4ogqmn) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/other/flutter-notes-known-issues-limitations.md#L24)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

What does that mean? How is the customer effected? BE will not send / drop stuff?
</blockquote></details>

@naorlevi please suggest


<!-- Sent from Reviewable.io -->

2024-07-23 16:48 UTC, MikePendo reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: 0 of 4 files reviewed, 22 unresolved discussions (waiting on @DavidPendo, @MaximShnirman, @naorlevi, @noambartouv, and @udilevin)

___
*[`other/flutter-notes-known-issues-limitations.md` line 2 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TEtdTDYs6J5qTKjD7:-O2VMIn2CwM00XAe7gEs:bccpql7) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/other/flutter-notes-known-issues-limitations.md#L2)):*
<details><summary><i>Previously, MaximShnirman (Maxim Shnirman) wrote…</i></summary><blockquote>

we are missing go router nested branching integration (shell support) 

1. need to add PendoNavigationObserver in each branch
2. need to add PendoNavigationObserver under the go router config 
3. need to create a 'static NestedBranchesObserver nestedBranchesObserver = NestedBranchesObserver();' 
4. under the build method call it like so 'nestedBranchesObserver.addListener(_router);' (where _router is the GoRouter one)
5. in case this was added to a stateful widget, call the following: 'pendoNestedBranchesObserver.removeListener(_router);' under the dispose method

example can be found in our host app, under: 'shell_route_navigation.dart' file
and also documentation of this is here: https://pendo-io.atlassian.net/browse/APP-100887
</blockquote></details>

1. mentioned 
2. I am not sure to which config u refer
3. I will put all the rest to code samples


<!-- Sent from Reviewable.io -->

2024-07-23 17:42 UTC, DavidPendo commented
*[`android/pnddocs/flutter-android.md` line 32 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2Vfg101rqhbPW-7GYO:-O2Vfg101rqhbPW-7GYP:bmczkda) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/608f9353a30f2c195de04cb573dbacabb8340483/android/pnddocs/flutter-android.md#L32)):*
> ```Markdown
> 
> - Minimum and compile SDK Version:  
> If applicable, set your app to be compiled with **compileSdkVersion 33** or higher and **minSdkVersion 21** or higher:
> ```

@MikePendo here please change it to 
```
If applicable, set your app to be **minSdkVersion 21** or higher:
```


<!-- Sent from Reviewable.io -->

2024-07-23 17:47 UTC, DavidPendo commented
*[`android/pnddocs/flutter-android.md` line 59 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TDhx6DFkHFWb6JVkj:-O2VgAj_6oT1YzKzrJSx:b-t21jnn) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L59)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

@DavidPendo maybe you can answer (I took it from the last Flutter integration)
</blockquote></details>

@MaximShnirman, this approach was chosen for all our framework integration documents for some reason. Maybe there is a better way to guide through installation instructions using the common part and then specify the platform specifics. I don't know if for know is better to keep it align with all the rest or do this change for Flutter only


<!-- Sent from Reviewable.io -->

2024-07-23 17:50 UTC, DavidPendo approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 21 unresolved discussions (waiting on @MaximShnirman, @MikePendo, @naorlevi, @noambartouv, and @udilevin)



<!-- Sent from Reviewable.io -->

2024-07-23 19:52 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 32 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2Vfg101rqhbPW-7GYO:-O2W8qtWD8fAsYVOtZa6:bb6un1j) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/608f9353a30f2c195de04cb573dbacabb8340483/android/pnddocs/flutter-android.md#L32)):*
<details><summary><i>Previously, DavidPendo wrote…</i></summary><blockquote>

@MikePendo here please change it to 
```
If applicable, set your app to be **minSdkVersion 21** or higher:
```
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-07-23 19:53 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 64 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TdVAI8cDKs8KqnmzK:-O2W92Ys5qceJP68qGS7:bb6un1j) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L64)):*
<details><summary><i>Previously, DavidPendo wrote…</i></summary><blockquote>

Is it worth mentioning that - you should perform the **setup** call as early as possible?

Just the **Add the following code in the `initState` method** is to abstract, like where the customer should add it?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-07-23 19:54 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 121 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TaM71DJ-TlDvatdji:-O2W9FnM6V8Z9xiE1PF5:b-rzif14) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L121)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

Let's combine the two lines before the code block. It looks weird as 1 line

typo: Add a click listener / add click listeners
</blockquote></details>

Didnt combine I think its fine 


<!-- Sent from Reviewable.io -->

2024-07-23 19:58 UTC, MikePendo commented
*[`android/pnddocs/flutter-android.md` line 140 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TdiuQ84yhyiKlbfNM:-O2WACDt-anS_5da8mtq:bb6un1j) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L140)):*
<details><summary><i>Previously, naorlevi (pippoTLV) wrote…</i></summary><blockquote>

ok. let's go with @noambartouv suggestion
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-07-23 21:10 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @DavidPendo, @MaximShnirman, @MikePendo, @naorlevi, and @udilevin)

___
*[`android/pnddocs/flutter-android.md` line 121 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TaM71DJ-TlDvatdji:-O2WNPaSE6rXgLql_PAc:b-wmj5y4) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L121)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

Didnt combine I think its fine
</blockquote></details>

typo still relevant though - should be: click listener (single) or click listeners (if multiple) [remove the 's' from clicks]
___
*[`android/pnddocs/flutter-android.md` line 140 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TdiuQ84yhyiKlbfNM:-O2WOYMo41kQD1XBqVWF:b-cr8hro) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/android/pnddocs/flutter-android.md#L140)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Styling is still a bit odd with the rest of the section. We should either move to be step #5 within section 2 and be indented correctly. Or even better (but more work) should move to be its own new section 3 (incrementing the other sections after) cause its not really part of section 2 called "Pendo SDK integration". track events are optional, not part of integration that the developer only performs once
___
*[`other/flutter-code-samples.md` line 39 at r5](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2WOsVH6rgOvqvm7qN8:-O2WOsVH6rgOvqvm7qN9:b-3ydbkq) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/bf7fe7e3ebe32366f675b12d823734a9e967c049/other/flutter-code-samples.md#L39)):*
> ```Markdown
>     @override
>     Widget build(BuildContext context) {
>         nestedBranchesObserver.addListener(_router); // listen to router chsnges
> ```

typo in comment 'changes'
___
*[`other/flutter-notes-known-issues-limitations.md` line 13 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TiKxJ7331ijCJKyUG:-O2WPKmdEz70tHIZzvHe:b5ry45m) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/other/flutter-notes-known-issues-limitations.md#L13)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I would add an additional 'br' before the last line, to separate it better from the list
___
*[`other/flutter-notes-known-issues-limitations.md` line 11 at r5](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2WPw641-g6ktpOdj50:-O2WPw656MlMdwkwnzYW:b2ntcfp) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/bf7fe7e3ebe32366f675b12d823734a9e967c049/other/flutter-notes-known-issues-limitations.md#L11)):*
> ```Markdown
> - `GoRouter` object should be added as listener to `NestedBranchesObserver()`, and removed on dispose 
> 
> please look at the [following sample code ](/other/flutter-code-samples.md)
> ```

capital 'p' in first word of the sentence

Alternative suggestion: (shorter)
See [sample code example](...)


<!-- Sent from Reviewable.io -->

2024-07-24 06:10 UTC, MaximShnirman approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 5 unresolved discussions (waiting on @MikePendo, @naorlevi, and @udilevin)



<!-- Sent from Reviewable.io -->

2024-07-24 06:11 UTC, MaximShnirman commented
*[`other/flutter-code-samples.md` line 47 at r5](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2YMI6jDYSwX9pfz2V2:-O2YMI6jDYSwX9pfz2V3:b-3hjb9f) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/bf7fe7e3ebe32366f675b12d823734a9e967c049/other/flutter-code-samples.md#L47)):*
> ```Markdown
> 
>     @override
>     void dispose() {
> ```

the dispose section exists only for StatefullWidgets. i think this should be mentioned as the customers will get confused


<!-- Sent from Reviewable.io -->

2024-07-24 06:12 UTC, MaximShnirman reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 7 unresolved discussions (waiting on @MikePendo, @naorlevi, and @udilevin)

___
*[`other/flutter-code-samples.md` line 8 at r5](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2YMU9B7tc39P8th3ao:-O2YMU9B7tc39P8th3ap:bgglfz7) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/bf7fe7e3ebe32366f675b12d823734a9e967c049/other/flutter-code-samples.md#L8)):*
> ```Markdown
> class NestedTabNavigationWidget extends StatelessWidget {
>     NestedTabNavigationExampleApp({super.key});
>     static NestedBranchesObserver nestedBranchesObserver = NestedBranchesObserver(); // create NestedBranchesObserver()
> ```

i would add new line between the declaration of the observer to make it more visible (nb)


<!-- Sent from Reviewable.io -->

2024-07-24 06:14 UTC, naorlevi commented
*[`other/flutter-notes-known-issues-limitations.md` line 24 at r2](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2TkYda6sV5M7y2IZdL:-O2YN1CC9p3iCzffoWf1:bl0z1i4) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/c4a45615b139937e77f422a38ca113db38f6b399/other/flutter-notes-known-issues-limitations.md#L24)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

@naorlevi please suggest
</blockquote></details>

They will not be able to tag pages and features


<!-- Sent from Reviewable.io -->

2024-07-24 06:14 UTC, naorlevi approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 6 unresolved discussions (waiting on @MikePendo, @noambartouv, and @udilevin)



<!-- Sent from Reviewable.io -->

2024-07-24 08:28 UTC, MaximShnirman approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 4 unresolved discussions (waiting on @MikePendo, @noambartouv, and @udilevin)



<!-- Sent from Reviewable.io -->

2024-07-24 08:48 UTC, noambartouv reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 3 unresolved discussions (waiting on @MikePendo and @udilevin)



<!-- Sent from Reviewable.io -->

2024-07-24 09:17 UTC, udilevin approved these changes
> Reviewed 1 of 2 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 3 unresolved discussions (waiting on @MikePendo and @noambartouv)



<!-- Sent from Reviewable.io -->

2024-07-24 10:37 UTC, MaximShnirman commented
*[`other/flutter-code-samples.md` line 3 at r9](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2ZJEbq30_wjlyA_NTK:-O2ZJEbq30_wjlyA_NTL:b6uiy6a) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/466a9ad980c202eadc6247cd47d577222ca1e0cf/other/flutter-code-samples.md#L3)):*
> ```Markdown
> 
> 
> The following example demonstrates Go_router integration with nested branches 
> ```

this file should appear in the main documentation as well
https://github.com/pendo-io/pendo-mobile-sdk/tree/APP-104740_flutter_codeless_docs


<!-- Sent from Reviewable.io -->

2024-07-24 10:38 UTC, MaximShnirman requested changes
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @DavidPendo, @MikePendo, @naorlevi, @noambartouv, and @udilevin)

___
*[`other/flutter-notes-known-issues-limitations.md` line 4 at r6](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157#-O2ZJP0bATMvonzKaKl0:-O2ZJP0bATMvonzKaKl1:bfhpxrb) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a4480ca5c97c75fd62e7d8ccd336afbe7ce6c03a/other/flutter-notes-known-issues-limitations.md#L4)):*
> ```Markdown
> 
> ## Navigation Libraries
> The page recognition solution supports the standard Flutter Navigator and GoRouter libraries. Integration with additional navigation frameworks is planned for future releases.
> ```

maybe this should appear on main file, not sure

https://github.com/pendo-io/pendo-mobile-sdk/tree/APP-104740_flutter_codeless_docs


<!-- Sent from Reviewable.io -->

2024-07-24 11:42 UTC, DavidPendo reviewed
> Reviewed 4 of 4 files at r5, 1 of 2 files at r6, 1 of 3 files at r7, 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @MikePendo, @naorlevi, @noambartouv, and @udilevin)



<!-- Sent from Reviewable.io -->

2024-07-24 11:58 UTC, MaximShnirman approved these changes
> Reviewed 1 of 3 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 3 unresolved discussions (waiting on @MikePendo, @naorlevi, @noambartouv, and @udilevin)



<!-- Sent from Reviewable.io -->

2024-07-24 12:15 UTC, DavidPendo approved these changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 3 unresolved discussions (waiting on @MikePendo, @naorlevi, @noambartouv, and @udilevin)



<!-- Sent from Reviewable.io -->

2024-07-24 12:17 UTC, udilevin approved these changes
> Reviewed 1 of 3 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)* status: all files reviewed, 3 unresolved discussions (waiting on @MikePendo, @naorlevi, and @noambartouv)



<!-- Sent from Reviewable.io -->

2024-07-24 12:17 UTC, udilevin commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>[merge]





<!-- Sent from Reviewable.io -->

2024-07-24 12:17 UTC, merged

2024-07-24 12:17 UTC, pendo-ops commented
All JIRA issue transitioned/labeled.
* [APP-104740](https://pendo-io.atlassian.net/browse/APP-104740): Jira Issue APP-104740: Changed to Resolved


Branch APP-104740_flutter_codeless_docs deleted