APP-88967 3.0 updated installation instructions
pendo-io/pendo-mobile-sdk pull request #79
Opened 2023-11-15 18:40 UTC by noambartouv

2023-11-15 22:26 UTC, TehilaTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @noambartouv)

___
*[`ios-integration/native-ios.md` line 148 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjK00VS-egdgbt4xP8m:-NjK00VS-egdgbt4xP8n:bpx5vk1) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/native-ios.md#L148)):*
> ```Markdown
> 
> <b>Note:</b> The `Scheme ID` can be found in your Pendo Subscription under the App Details section.
> ```

maybe just add 'Subscription Settings' (instead of Pendo Subscription) and 'App Details' so it will match exactly the web terms 


<!-- Sent from Reviewable.io -->

2023-11-16 09:02 UTC, randmaayan approved these changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: all files reviewed, 1 unresolved discussion (waiting on @noambartouv)



<!-- Sent from Reviewable.io -->

2023-11-16 15:02 UTC, randmaayan reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: all files reviewed, 2 unresolved discussions (waiting on @noambartouv)

___
*[`android-integration/xamarin_maui-android.md` line 45 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNdlRVBkZNe76AwihL:-NjNdlRVBkZNe76AwihM:bd3rck) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/android-integration/xamarin_maui-android.md#L45)):*
> ```Markdown
>         if (pendo != null) {            
>             string apiKey = "YOUR_API_KEY_HERE";
>             Pendo.Setup(apiKey);
> ```

please lowercase Pendo here 


<!-- Sent from Reviewable.io -->

2023-11-16 15:05 UTC, MikePendo commented
*[`ios-integration/native-ios.md` line 124 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNdYXF8M20_XvUiMPA:-NjNdYXF8M20_XvUiMPB:b-k3smgv) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/native-ios.md#L124)):*
> ```Markdown
> ### Supporting SwiftUI
> 
> To support SwiftUI, the `pendoEnableSwiftUI()` modifier must be called on each of the `rootViews` in your app. See example below:
> ```

Ok somehow they got confused by the ` on each of the rootViews`. Maybe we can change it to:
`To support SwiftUI, the pendoEnableSwiftUI() modifier must be applied  to your main rootView of your app. (In case of multiple rootViews for instance if you have multiple UIHostingControllers the modifier should be applied to each rootView parameter)


<!-- Sent from Reviewable.io -->

2023-11-16 15:08 UTC, MikePendo commented
*[`ios-integration/native-ios.md` line 256 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNew6SCRveCa2wpfZ9:-NjNew6SCRveCa2wpfZA:b-7jisy3) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/native-ios.md#L256)):*
> ```Markdown
> 
> ### SwiftUI 
> - Clickable elements (e.x. Buttons / TapGestures) have a transparent background color  or that are created without a set background color (e.x. VStack or HStack) may encounter issues with identification by our SDK. To resolve this issue invoke the `pendoRecognizeClickAnalytics()` API on the `View` of this element.
> ```

Maybe lets skip the long explanation and just lets write if clickable element is not recognized as clickable apply the following modifier 


<!-- Sent from Reviewable.io -->

2023-11-16 15:11 UTC, MikePendo commented
*[`ios-integration/native-ios.md` line 260 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNff9C5rZi-huD88l8:-NjNff9C5rZi-huD88l9:b-o2wvgt) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/native-ios.md#L260)):*
> ```Markdown
> - The `iOS 16 Navigation APIs` are not supported at the moment.
> 
> - The `PresentationContainer` is not supported at the moment.
> ```

I must admit I dont even remember what is `PresentationContainer ` :)
BUT WE MUST mention the Swiftui navigation (other wise it will not work )


<!-- Sent from Reviewable.io -->

2023-11-16 15:13 UTC, MikePendo reviewed
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: all files reviewed, 6 unresolved discussions (waiting on @noambartouv)



<!-- Sent from Reviewable.io -->

2023-11-16 15:43 UTC, udilevin commented on android-integration/xamarin_forms-android.md
should be pendo-xamarin-forms plugin requires ...

2023-11-16 15:51 UTC, udilevin commented
*[`android-integration/xamarin_maui-android.md` line 36 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNoupsBgmK4xl5GSV4:-NjNoupsBgmK4xl5GSV5:bb5odp5) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/android-integration/xamarin_maui-android.md#L36)):*
> ```Markdown
>     In the **protected override void OnStart()** method, add the following code:
> 
>     ```c#
> ```

Think we need to add the import statement as well (we have 3 artifacts with 3 different namespaces).


<!-- Sent from Reviewable.io -->

2023-11-16 15:52 UTC, udilevin commented
*[`android-integration/xamarin_maui-android.md` line 148 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNp8Eg4imi9fQ8KZky:-NjNp8Eg4imi9fQ8KZkz:bndts0r) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/android-integration/xamarin_maui-android.md#L148)):*
> ```Markdown
> 
> - For technical issues please [review open issues](https://github.com/pendo-io/pendo-mobile-sdk/issues) or [submit a new issue](https://github.com/pendo-io/pendo-mobile-sdk/issues).
> - Release notes can be found [here](https://developers.pendo.io/category/mobile-sdk/).
> ```

remove the Dex issues since in Xamarin/Maui it's just a click of a button.


<!-- Sent from Reviewable.io -->

2023-11-16 15:56 UTC, udilevin commented
*[`ios-integration/native-ios.md` line 123 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNpqDd4DfOG9YHgsnA:-NjNpqDd4DfOG9YHgsnB:b-b1thpz) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/native-ios.md#L123)):*
> ```Markdown
> 
> ### Supporting SwiftUI
> ```

The phrase "on each of the `rootViews` "  is very confusing...i was on a call with a customer that called the modifier on every view.
We should clarify somehow...maybe  modifier must be called on your application root view (in case your app is using multiple root views, use the modifier on each of them)...


<!-- Sent from Reviewable.io -->

2023-11-16 16:02 UTC, udilevin commented
*[`ios-integration/xamarin_forms-ios.md` line 143 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNr7hK2wqOPOpWiw9x:-NjNr7hL975x3TcFWA-g:b-vdo29n) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/xamarin_forms-ios.md#L143)):*
> ```Markdown
> 
> ## Troubleshooting
> ```

These should not happen anymore since we are not using the keychain anymore.  We can remove it


<!-- Sent from Reviewable.io -->

2023-11-16 16:02 UTC, udilevin commented
*[`ios-integration/xamarin_maui-ios.md` line 25 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNrdkV0xYihC1hrhQ-:-NjNrdkV0xYihC1hrhQ0:b-gtm84g) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/xamarin_maui-ios.md#L25)):*
> ```Markdown
>     ``` 
> ```

Maybe add the namespace/import as well 


<!-- Sent from Reviewable.io -->

2023-11-16 16:03 UTC, udilevin commented
*[`ios-integration/xamarin_maui-ios.md` line 121 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNrhGhAIEiR6iGuLr7:-NjNrhGhAIEiR6iGuLr8:br0ff9b) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/xamarin_maui-ios.md#L121)):*
> ```Markdown
>         {
>             if (url.Scheme.Contains("pendo"))
>             {
> ```

Please add the comment about other platforms here why checking for null


<!-- Sent from Reviewable.io -->

2023-11-16 16:04 UTC, udilevin commented
*[`ios-integration/xamarin_forms-ios.md` line 2 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNrydW5wjsBZsheXII:-NjNrydW5wjsBZsheXIJ:b-xv9aiw) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/xamarin_forms-ios.md#L2)):*
> ```Markdown
> # Xamarin forms
> ```

Reminding you about the minimum requirement for Xamarin Forms with this release 5.0.0.2612. I think it should be mentioned here and in the Android as well


<!-- Sent from Reviewable.io -->

2023-11-16 16:08 UTC, udilevin commented
*[`migration-docs/flutter-2.x-to-3.x-migration.md` line 31 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNt0Yi9PHMth0EZ7Ar:-NjNt0Yi9PHMth0EZ7As:b-d930ra) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/migration-docs/flutter-2.x-to-3.x-migration.md#L31)):*
> ```Markdown
> <td align=center><b>initSDK </td>
> <td>
> ```

Please note that in 3.0 PendoFlutterPlugin was renamed to PendoSDK. Please update all APIs belowe


<!-- Sent from Reviewable.io -->

2023-11-16 16:10 UTC, udilevin commented
*[`migration-docs/maui-2.x-to-3.x-migration.md` line 20 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNtD-I6kumrLiEoRZp:-NjNtD-I6kumrLiEoRZq:b1lg4q4) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/migration-docs/maui-2.x-to-3.x-migration.md#L20)):*
> ```Markdown
> 
> <b>3.x:</b> `1.8.0`
> ```

Pendo MAUI now requires  with .NET7 (2.x required .NET 6)


<!-- Sent from Reviewable.io -->

2023-11-16 16:16 UTC, udilevin commented
*[`migration-docs/react-native-2.x-to-3.x-migration.md` line 39 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNtXg23MCpSj0fLrzq:-NjNtXg23MCpSj0fLrzr:b-m995t7) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/migration-docs/react-native-2.x-to-3.x-migration.md#L39)):*
> ```Markdown
> // in the file where the NavigationContainer is created
> import {withPendoRN} from 'rn-pendo-sdk'    
> ```

This is the wrong old integration:
Add the following code in the method that creates the \`NavigationContainer\` (e.g. RootNavigator)   
and returns the \`NavigationContainer\` wrapped using withPendoRN:  
  
#### IMPORTANT: This function must be called \*\*after\*\* PendoSDK.setup completes  
  

function RootNavigator(props) {  
  const navigationRef = useRef();  
return (    <NavigationContainer      
ref={navigationRef}  
      onStateChange={()=> {        
const state = navigationRef.current.getRootState()        
props.onStateChange(state);     
 }}      
onReady ={()=>{  
        const state = navigationRef.current.getRootState()        
props.onStateChange(state);     
 }}>{MainStackScreen()}</NavigationContainer >  )};  
  

export default withPendoRN(RootNavigator);

In the new integration you should indicate they should remove the onReady and onStateChange


<!-- Sent from Reviewable.io -->

2023-11-16 16:16 UTC, udilevin commented
*[`migration-docs/xamarin-forms-2.x-to-3.x-migration.md` line 25 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNusHJ288_R0Q9Bx7g:-NjNusHJ288_R0Q9Bx7h:b-9l5u5q) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/migration-docs/xamarin-forms-2.x-to-3.x-migration.md#L25)):*
> ```Markdown
> 
> <!--- new row --->
> ```

also Android V13  (API Level 33)


<!-- Sent from Reviewable.io -->

2023-11-16 16:56 UTC, MikePendo commented
*[`migration-docs/react-native-2.x-to-3.x-migration.md` line 39 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNtXg23MCpSj0fLrzq:-NjO2xLc1CU7Sgziy0nY:b-obf0nk) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/migration-docs/react-native-2.x-to-3.x-migration.md#L39)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

This is the wrong old integration:
Add the following code in the method that creates the \`NavigationContainer\` (e.g. RootNavigator)   
and returns the \`NavigationContainer\` wrapped using withPendoRN:  
  
#### IMPORTANT: This function must be called \*\*after\*\* PendoSDK.setup completes  
  

function RootNavigator(props) {  
  const navigationRef = useRef();  
return (    <NavigationContainer      
ref={navigationRef}  
      onStateChange={()=> {        
const state = navigationRef.current.getRootState()        
props.onStateChange(state);     
 }}      
onReady ={()=>{  
        const state = navigationRef.current.getRootState()        
props.onStateChange(state);     
 }}>{MainStackScreen()}</NavigationContainer >  )};  
  

export default withPendoRN(RootNavigator);

In the new integration you should indicate they should remove the onReady and onStateChange
</blockquote></details>

I dont think we should mention this integration at all 


<!-- Sent from Reviewable.io -->

2023-11-16 19:19 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: 1 of 14 files reviewed, 18 unresolved discussions (waiting on @MikePendo, @randmaayan, @TehilaTaub, and @udilevin)

___
*[`android-integration/xamarin_forms-android.md` line 21 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#gh-1395929927:-NjOEnaK7mC_D-uPVEGX:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/android-integration/xamarin_forms-android.md#L21)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

should be pendo-xamarin-forms plugin requires ...
</blockquote></details>

Done.
___
*[`android-integration/xamarin_maui-android.md` line 36 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNoupsBgmK4xl5GSV4:-NjOJQHn5kLZRZz-u-On:b3u0m5c) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/android-integration/xamarin_maui-android.md#L36)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Think we need to add the import statement as well (we have 3 artifacts with 3 different namespaces).
</blockquote></details>

Done

There is already an import statement a few lines above (```using PendoMAUIPlugin;```)
I went over all of code blocks for MAUI and Forms to make sure each code block has an import
___
*[`android-integration/xamarin_maui-android.md` line 148 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNp8Eg4imi9fQ8KZky:-NjOOi_d2V9glIecwtiV:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/android-integration/xamarin_maui-android.md#L148)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

remove the Dex issues since in Xamarin/Maui it's just a click of a button.
</blockquote></details>

Done.
___
*[`ios-integration/native-ios.md` line 13 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNpI5F9DNnNMNvHTsp:-NjOOqZX2zmg1nehoZyf:b-qsq1up) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/native-ios.md#L13)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Why are we combining swift ui with native? I think we should have 2 files and write at the top ... if you are looking for swiftUI instructions click here...(in native file) and if you are looking for UIKit instructions click here (in swiftui file)
</blockquote></details>

90% of installation is the same and its now the same build. A bunch of our customer app are a mix of UIKit and SwiftUI and we should address them together. Seems less confusing to me
 
The only 3 additions for SwiftUI are:
- create the appdelegate file if it doesn't exist
- add the pendoEnableSwiftUI on rootviews
- Force openURL to be called for pure SwiftUI apps  
___
*[`ios-integration/native-ios.md` line 123 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNpqDd4DfOG9YHgsnA:-NjOSk6xDpaUpNo95ALz:b9dq7nl) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/native-ios.md#L123)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

The phrase "on each of the `rootViews` "  is very confusing...i was on a call with a customer that called the modifier on every view.
We should clarify somehow...maybe  modifier must be called on your application root view (in case your app is using multiple root views, use the modifier on each of them)...
</blockquote></details>

:thumbsup:  See suggested edit
___
*[`ios-integration/native-ios.md` line 124 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNdYXF8M20_XvUiMPA:-NjOSpMRA8yDH1HZvgTP:b9dq7nl) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/native-ios.md#L124)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

Ok somehow they got confused by the ` on each of the rootViews`. Maybe we can change it to:
`To support SwiftUI, the pendoEnableSwiftUI() modifier must be applied  to your main rootView of your app. (In case of multiple rootViews for instance if you have multiple UIHostingControllers the modifier should be applied to each rootView parameter)
</blockquote></details>

:thumbsup:  See suggested edit
___
*[`ios-integration/xamarin_forms-ios.md` line 143 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNr7hK2wqOPOpWiw9x:-NjOXXzX25Az3f5IsAax:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/xamarin_forms-ios.md#L143)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

These should not happen anymore since we are not using the keychain anymore.  We can remove it
</blockquote></details>

Done.
___
*[`ios-integration/xamarin_maui-ios.md` line 121 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNrhGhAIEiR6iGuLr7:-NjOXksY9GUnHTmM4t-R:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/xamarin_maui-ios.md#L121)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Please add the comment about other platforms here why checking for null
</blockquote></details>

Done.
___
*[`migration-docs/flutter-2.x-to-3.x-migration.md` line 31 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNt0Yi9PHMth0EZ7Ar:-NjO9wK9AUIpgp6OB82S:b-rsgilj) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/migration-docs/flutter-2.x-to-3.x-migration.md#L31)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Please note that in 3.0 PendoFlutterPlugin was renamed to PendoSDK. Please update all APIs belowe
</blockquote></details>

When did we approve that? That is a breaking change for all Flutter customers (without this change the migration for most flutter customers from 2.x to 3.x will be transparent)
___
*[`migration-docs/maui-2.x-to-3.x-migration.md` line 20 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNtD-I6kumrLiEoRZp:-NjOYZuKAsy8f1U-gevf:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/migration-docs/maui-2.x-to-3.x-migration.md#L20)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Pendo MAUI now requires  with .NET7 (2.x required .NET 6)
</blockquote></details>

Done.
___
*[`migration-docs/xamarin-forms-2.x-to-3.x-migration.md` line 25 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNusHJ288_R0Q9Bx7g:-NjOYp6jAOWbeqGA92Ki:b-fyjer3) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/migration-docs/xamarin-forms-2.x-to-3.x-migration.md#L25)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

also Android V13  (API Level 33)
</blockquote></details>

What was the previous minimum? API Level 21? Thats quite a jump!


<!-- Sent from Reviewable.io -->

2023-11-16 22:20 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: 1 of 26 files reviewed, 17 unresolved discussions (waiting on @MikePendo, @randmaayan, @TehilaTaub, and @udilevin)

___
*[`ios-integration/native-ios.md` line 256 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNew6SCRveCa2wpfZ9:-NjP0tZJ2VmJLiBm_wJs:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/native-ios.md#L256)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

Maybe lets skip the long explanation and just lets write if clickable element is not recognized as clickable apply the following modifier
</blockquote></details>

Done.
___
*[`ios-integration/native-ios.md` line 260 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNff9C5rZi-huD88l8:-NjP0vy60U2-b-7diKD2:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/native-ios.md#L260)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

I must admit I dont even remember what is `PresentationContainer ` :)
BUT WE MUST mention the Swiftui navigation (other wise it will not work )
</blockquote></details>

Done.
___
*[`ios-integration/xamarin_forms-ios.md` line 2 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNrydW5wjsBZsheXII:-NjP6PAX4FI2-4dWykOf:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/xamarin_forms-ios.md#L2)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Reminding you about the minimum requirement for Xamarin Forms with this release 5.0.0.2612. I think it should be mentioned here and in the Android as well
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-17 12:28 UTC, udilevin commented
*[`migration-docs/xamarin-forms-2.x-to-3.x-migration.md` line 25 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNusHJ288_R0Q9Bx7g:-NjSF9rw7b_Dk3btcTyR:buu1nfs) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/migration-docs/xamarin-forms-2.x-to-3.x-migration.md#L25)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

What was the previous minimum? API Level 21? Thats quite a jump!
</blockquote></details>

It’s the target not the minimum


<!-- Sent from Reviewable.io -->

2023-11-17 12:28 UTC, udilevin reviewed
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: 1 of 26 files reviewed, 9 unresolved discussions (waiting on @MikePendo, @noambartouv, @randmaayan, and @TehilaTaub)



<!-- Sent from Reviewable.io -->

2023-11-17 13:24 UTC, MikePendo commented
*[`ios-integration/flutter-ios.md` line 16 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjSRrK-C26g_E6mBkCi:-NjSRrK03KqpVDVG0UBo:b-71dmw1) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a8ca8179bc1a3d2d55bed925b386cea6c3f334b7/ios-integration/flutter-ios.md#L16)):*
> ```Markdown
>     import 'package:pendo_sdk/pendo_sdk.dart';
>     var pendoKey = 'YOUR_API_KEY_HERE';
>     await PendoFlutterPlugin.setup(pendoKey);
> ```

I think the name was change to Pendo SDK (same apply for Android)


<!-- Sent from Reviewable.io -->

2023-11-17 13:25 UTC, MikePendo commented
*[`ios-integration/flutter-ios.md` line 34 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjSS5zl096GJC93_jtl:-NjSS5zl096GJC93_jtm:b-awf1xq) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a8ca8179bc1a3d2d55bed925b386cea6c3f334b7/ios-integration/flutter-ios.md#L34)):*
> ```Markdown
> ```dart
>     import 'package:pendo_sdk/pendo_sdk.dart';
>     await PendoFlutterPlugin.track('name', { 'firstProperty': 'firstPropertyValue', 'secondProperty': 'secondPropertyValue'});
> ```

@noambartouv @udilevin do we need to mention track events?


<!-- Sent from Reviewable.io -->

2023-11-17 13:49 UTC, MikePendo commented
*[`ios-integration/xamarin_forms-ios.md` line 46 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNqvUP4MVMsQojTwum:-NjSXgLD1muevOgg_1MV:bvrikxr) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/xamarin_forms-ios.md#L46)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

I think we should rename this namespace as well something like  PendoXamarinForms (NB)
</blockquote></details>

why not PendoSDK ?


<!-- Sent from Reviewable.io -->

2023-11-17 18:00 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: 1 of 26 files reviewed, 8 unresolved discussions (waiting on @MikePendo, @randmaayan, @TehilaTaub, and @udilevin)

___
*[`ios-integration/flutter-ios.md` line 16 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjSRrK-C26g_E6mBkCi:-NjTPu2449pLmQSaMv-3:bpeiog9) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a8ca8179bc1a3d2d55bed925b386cea6c3f334b7/ios-integration/flutter-ios.md#L16)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

I think the name was change to Pendo SDK (same apply for Android)
</blockquote></details>

See slack for open discussion if this should be reverted or not
___
*[`ios-integration/flutter-ios.md` line 34 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjSS5zl096GJC93_jtl:-NjTPiklDTmsREz205Wy:bgnd4he) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a8ca8179bc1a3d2d55bed925b386cea6c3f334b7/ios-integration/flutter-ios.md#L34)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

@noambartouv @udilevin do we need to mention track events?
</blockquote></details>

the codeless solution is a closed beta and the installation instructions for it will be sent via email as far as I've heard. So the general installation instructions are for track event only solution and should remain the same.
___
*[`ios-integration/xamarin_forms-ios.md` line 46 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNqvUP4MVMsQojTwum:-NjTQzSp3AP1vjsdYGM-:b-icypni) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/xamarin_forms-ios.md#L46)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

why not PendoSDK ?
</blockquote></details>

let's continue the disscussion about this and flutter change in slack
___
*[`migration-docs/xamarin-forms-2.x-to-3.x-migration.md` line 25 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNusHJ288_R0Q9Bx7g:-NjTQDsS1WRZKyWzF17w:btqmkin) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/migration-docs/xamarin-forms-2.x-to-3.x-migration.md#L25)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

It’s the target not the minimum
</blockquote></details>

So what was the previous target API level?
also are we sure we need it? Based on Google's Play Store: "Starting August 31, 2023: New apps must target Android 13 (API level 33) or higher;" Or because not all all apps are distrubted via play store?


<!-- Sent from Reviewable.io -->

2023-11-20 19:10 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: 1 of 27 files reviewed, 6 unresolved discussions (waiting on @MikePendo, @randmaayan, @TehilaTaub, and @udilevin)

___
*[`ios-integration/flutter-ios.md` line 16 at r3](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjSRrK-C26g_E6mBkCi:-NjhqznVDo7Gz4oPVxx9:bb6un1j) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a8ca8179bc1a3d2d55bed925b386cea6c3f334b7/ios-integration/flutter-ios.md#L16)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

See slack for open discussion if this should be reverted or not
</blockquote></details>

Done
___
*[`ios-integration/native-ios.md` line 13 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNpI5F9DNnNMNvHTsp:-Nji0PQi-9wgYDxXWhqe:bnz1cb3) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/native-ios.md#L13)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

90% of installation is the same and its now the same build. A bunch of our customer app are a mix of UIKit and SwiftUI and we should address them together. Seems less confusing to me
 
The only 3 additions for SwiftUI are:
- create the appdelegate file if it doesn't exist
- add the pendoEnableSwiftUI on rootviews
- Force openURL to be called for pure SwiftUI apps
</blockquote></details>

Discussed. Leaving as is for now.
___
*[`ios-integration/xamarin_maui-ios.md` line 25 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNrdkV0xYihC1hrhQ-:-Nji0gVZ12fF8RHJIZxk:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/ios-integration/xamarin_maui-ios.md#L25)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Maybe add the namespace/import as well
</blockquote></details>

Done.
___
*[`migration-docs/flutter-2.x-to-3.x-migration.md` line 31 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNt0Yi9PHMth0EZ7Ar:-Nji7k5Y5WCAZYWGY1zI:bp1oiq6) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/migration-docs/flutter-2.x-to-3.x-migration.md#L31)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

When did we approve that? That is a breaking change for all Flutter customers (without this change the migration for most flutter customers from 2.x to 3.x will be transparent)
</blockquote></details>

Discussed. Done
___
*[`migration-docs/react-native-2.x-to-3.x-migration.md` line 39 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNtXg23MCpSj0fLrzq:-Nji-YDwB-I1cDhvMF7Y:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/migration-docs/react-native-2.x-to-3.x-migration.md#L39)):*
<details><summary><i>Previously, MikePendo (Michael Rozenblat) wrote…</i></summary><blockquote>

I dont think we should mention this integration at all
</blockquote></details>

Done.
___
*[`migration-docs/xamarin-forms-2.x-to-3.x-migration.md` line 25 at r1](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjNusHJ288_R0Q9Bx7g:-Nji82vj2s_t6hN1VQT7:bb6un1j) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/a9d0b50de4718c921c71c354562e176fef4e1d38/migration-docs/xamarin-forms-2.x-to-3.x-migration.md#L25)):*
<details><summary><i>Previously, noambartouv wrote…</i></summary><blockquote>

So what was the previous target API level?
also are we sure we need it? Based on Google's Play Store: "Starting August 31, 2023: New apps must target Android 13 (API level 33) or higher;" Or because not all all apps are distrubted via play store?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-20 19:42 UTC, TehilaTaub approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-:-NjiFFaJ77l8c22L0PLo:bnfp4nl)* status: 1 of 27 files reviewed, 6 unresolved discussions (waiting on @MikePendo, @randmaayan, and @udilevin)



<!-- Sent from Reviewable.io -->

2023-11-21 01:24 UTC, MikePendo commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2023-11-21 01:25 UTC, MikePendo approved these changes
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: 1 of 27 files reviewed, 5 unresolved discussions (waiting on @randmaayan, @TehilaTaub, and @udilevin)



<!-- Sent from Reviewable.io -->

2023-11-21 08:48 UTC, udilevin requested changes
> Reviewed 1 of 13 files at r2, 2 of 22 files at r3, 4 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: 8 of 27 files reviewed, 4 unresolved discussions (waiting on @MikePendo, @noambartouv, @randmaayan, and @TehilaTaub)

___
*[`android-integration/android_sdk_manual_installation.md` line 21 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-Njl12JD90lgKA8pyezF:-Njl12JD90lgKA8pyezG:b-y4u3bu) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/420b769c5ed91bb9fd3f9d4ac2cdf6dc3f442075/android-integration/android_sdk_manual_installation.md#L21)):*
> ```Markdown
> 
> 4. Specify the version number for the Pendo dependency in the gradle file:
> ```

suggest updating the sample version  to 3.0.0.x
___
*[`android-integration/expo_rn-android.md` line 141 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-Njl1IqpA20GJsIXii62:-Njl1IqpA20GJsIXii63:b-7zf9zz) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/420b769c5ed91bb9fd3f9d4ac2cdf6dc3f442075/android-integration/expo_rn-android.md#L141)):*
> ```Markdown
> 
> - For technical issues please [review open issues](https://github.com/pendo-io/pendo-mobile-sdk/issues) or [submit a new issue](https://github.com/pendo-io/pendo-mobile-sdk/issues).
> - Release notes can be found [here](https://developers.pendo.io/category/mobile-sdk/).
> ```

 Dex issues can not be addressed in expo via this link. Please remove it. 
___
*[`android-integration/expo_rnn-android.md` line 105 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-Njl1U5J3QSRkZdyr_JS:-Njl1U5J3QSRkZdyr_JT:b7qqxfc) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/420b769c5ed91bb9fd3f9d4ac2cdf6dc3f442075/android-integration/expo_rnn-android.md#L105)):*
> ```Markdown
> 
> - For technical issues please [review open issues](https://github.com/pendo-io/pendo-mobile-sdk/issues) or [submit a new issue](https://github.com/pendo-io/pendo-mobile-sdk/issues).
> - Release notes can be found [here](https://developers.pendo.io/category/mobile-sdk/).
> ```

Dex issues should be removed
___
*[`android-integration/native-android.md` line 4 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-Njl1bjND9myrUCluBKE:-Njl1bjND9myrUCluBKF:bn00bb3) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/420b769c5ed91bb9fd3f9d4ac2cdf6dc3f442075/android-integration/native-android.md#L4)):*
> ```Markdown
> 
> ### Requirements
> ```

@DavidFaermanPendo What is the minimum kotlin version? I remember something about 1.8 not 1.9


<!-- Sent from Reviewable.io -->

2023-11-21 15:10 UTC, pendo-ops commented
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[1bd3b8c](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/1bd3b8c60037fb5bcf19fe676257d6e0117dc6c5)

2023-11-21 18:01 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: 8 of 27 files reviewed, 3 unresolved discussions (waiting on @DavidFaermanPendo, @MikePendo, @randmaayan, @TehilaTaub, and @udilevin)

___
*[`android-integration/expo_rn-android.md` line 141 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-Njl1IqpA20GJsIXii62:-Njn1ARc3k8CEaTtY6ly:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/420b769c5ed91bb9fd3f9d4ac2cdf6dc3f442075/android-integration/expo_rn-android.md#L141)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Dex issues can not be addressed in expo via this link. Please remove it.
</blockquote></details>

Done.
___
*[`android-integration/expo_rnn-android.md` line 105 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-Njl1U5J3QSRkZdyr_JS:-Njn1E9fD9KS6hickaHM:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/420b769c5ed91bb9fd3f9d4ac2cdf6dc3f442075/android-integration/expo_rnn-android.md#L105)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Dex issues should be removed
</blockquote></details>

Done.
___
*[`android-integration/native-android.md` line 4 at r4](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-Njl1bjND9myrUCluBKE:-Njn1FlA96WWkNuUqG96:be2pw15) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/420b769c5ed91bb9fd3f9d4ac2cdf6dc3f442075/android-integration/native-android.md#L4)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

@DavidFaermanPendo What is the minimum kotlin version? I remember something about 1.8 not 1.9
</blockquote></details>

We needed to update the SDK to 1.9 but checking with apps that depend on 1.8 seem to work. Guild decision to officially support 1.9 and they can use 1.8 at their own peril 


<!-- Sent from Reviewable.io -->

2023-11-21 18:03 UTC, pendo-ops commented
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[1bd3b8c](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/1bd3b8c60037fb5bcf19fe676257d6e0117dc6c5)

2023-11-21 19:39 UTC, pendo-ops commented
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[1bd3b8c](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/1bd3b8c60037fb5bcf19fe676257d6e0117dc6c5)
[757478b](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/757478bc2a0a4ad361d339987f5b012c32a3444e)

2023-11-21 23:03 UTC, pendo-ops commented
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[1bd3b8c](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/1bd3b8c60037fb5bcf19fe676257d6e0117dc6c5)
[757478b](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/757478bc2a0a4ad361d339987f5b012c32a3444e)
[d5ca623](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/d5ca6233a6b49bb4d0dfe36d6654e0d10efb6ee5)

2023-11-21 23:15 UTC, pendo-ops commented
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[1bd3b8c](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/1bd3b8c60037fb5bcf19fe676257d6e0117dc6c5)
[757478b](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/757478bc2a0a4ad361d339987f5b012c32a3444e)
[d5ca623](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/d5ca6233a6b49bb4d0dfe36d6654e0d10efb6ee5)
[0d38671](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/0d38671236011583820b25da19e032c1c3560ad8)

2023-11-21 23:30 UTC, pendo-ops commented
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[1bd3b8c](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/1bd3b8c60037fb5bcf19fe676257d6e0117dc6c5)
[757478b](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/757478bc2a0a4ad361d339987f5b012c32a3444e)
[d5ca623](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/d5ca6233a6b49bb4d0dfe36d6654e0d10efb6ee5)
[0d38671](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/0d38671236011583820b25da19e032c1c3560ad8)
[10fe652](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/10fe652ab95a006dfd4446e47b6b63cc73134a03)

2023-11-21 23:31 UTC, pendo-ops commented
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[1bd3b8c](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/1bd3b8c60037fb5bcf19fe676257d6e0117dc6c5)
[757478b](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/757478bc2a0a4ad361d339987f5b012c32a3444e)
[d5ca623](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/d5ca6233a6b49bb4d0dfe36d6654e0d10efb6ee5)
[0d38671](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/0d38671236011583820b25da19e032c1c3560ad8)
[10fe652](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/10fe652ab95a006dfd4446e47b6b63cc73134a03)
[4bfe8b1](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/4bfe8b135cd02daa73cf0efca35a872982c67bcf)

2023-11-21 23:38 UTC, pendo-ops commented
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[1bd3b8c](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/1bd3b8c60037fb5bcf19fe676257d6e0117dc6c5)
[757478b](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/757478bc2a0a4ad361d339987f5b012c32a3444e)
[d5ca623](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/d5ca6233a6b49bb4d0dfe36d6654e0d10efb6ee5)
[0d38671](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/0d38671236011583820b25da19e032c1c3560ad8)
[10fe652](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/10fe652ab95a006dfd4446e47b6b63cc73134a03)
[4bfe8b1](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/4bfe8b135cd02daa73cf0efca35a872982c67bcf)
[3c2dfbd](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/3c2dfbdc06c39398a62093b419ea9d5775c3ed24)

2023-11-21 23:40 UTC, pendo-ops commented
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[1bd3b8c](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/1bd3b8c60037fb5bcf19fe676257d6e0117dc6c5)
[757478b](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/757478bc2a0a4ad361d339987f5b012c32a3444e)
[d5ca623](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/d5ca6233a6b49bb4d0dfe36d6654e0d10efb6ee5)
[0d38671](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/0d38671236011583820b25da19e032c1c3560ad8)
[10fe652](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/10fe652ab95a006dfd4446e47b6b63cc73134a03)
[4bfe8b1](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/4bfe8b135cd02daa73cf0efca35a872982c67bcf)
[3c2dfbd](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/3c2dfbdc06c39398a62093b419ea9d5775c3ed24)
[f1951e2](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/f1951e2de1eb2a490408a063c887104309b0c39c)

2023-11-21 23:42 UTC, pendo-ops commented
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[1bd3b8c](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/1bd3b8c60037fb5bcf19fe676257d6e0117dc6c5)
[757478b](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/757478bc2a0a4ad361d339987f5b012c32a3444e)
[d5ca623](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/d5ca6233a6b49bb4d0dfe36d6654e0d10efb6ee5)
[0d38671](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/0d38671236011583820b25da19e032c1c3560ad8)
[10fe652](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/10fe652ab95a006dfd4446e47b6b63cc73134a03)
[4bfe8b1](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/4bfe8b135cd02daa73cf0efca35a872982c67bcf)
[3c2dfbd](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/3c2dfbdc06c39398a62093b419ea9d5775c3ed24)
[f1951e2](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/f1951e2de1eb2a490408a063c887104309b0c39c)
[f820c76](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/f820c76860c719cd34d82dd55d1ad969aaaa2b01)

2023-11-22 09:11 UTC, udilevin commented
*[`android-integration/expo_rn-android.md` line 3 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqHyUa4RrbF-qC19tn:-NjqHyUa4RrbF-qC19to:b-qv5bn8) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/android-integration/expo_rn-android.md#L3)):*
> ```Markdown
> # Expo using React Navigation
> 
> >[!IMPORTANT]
> ```

We should probably mention that we currently don't support codeless solution for Expo Router


<!-- Sent from Reviewable.io -->

2023-11-22 09:19 UTC, udilevin commented
*[`android-integration/native-android.md` line 26 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqJx1f2XxMtXloACxK:-NjqJx1f2XxMtXloACxL:b25j41e) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/android-integration/native-android.md#L26)):*
> ```Markdown
> 
>     ```shell
>     dependencies {
> ```

needs to be 3.0.+


<!-- Sent from Reviewable.io -->

2023-11-22 09:27 UTC, udilevin commented
*[`android-integration/rn-android.md` line 5 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqLa4r44TNjHAGWLW-:-NjqLa4r44TNjHAGWLW0:bu0t0c4) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/android-integration/rn-android.md#L5)):*
> ```Markdown
> >[!NOTE]
> >Pendo now supports Expo SDK 41-48. Follow [Expo Integration](/android-integration/expo_rn-android.md) instructions.
> ```

Like with Expo, we should probably mention here: 
Pendo supports RN using react-navigation 5+.<br>
For the codeless solution to work, all the elements *MUST be wrapped in react-native ui components*.<br>
As with other analytics tools, we are dependent on react-navigation [screen change callbacks](https://reactnavigation.org/docs/screen-tracking/)
which means that codeless tracking analytics is available for screen components only.


<!-- Sent from Reviewable.io -->

2023-11-22 09:28 UTC, udilevin commented
*[`android-integration/rn-android.md` line 9 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqLrAT4ejMKGK2Fper:-NjqLrAT4ejMKGK2Fpes:bij5h3s) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/android-integration/rn-android.md#L9)):*
> ```Markdown
> ## Step 1. Install Pendo SDK
> ```

you can use the same terms and style like expo:
use one of your package managers
```
npm i rn-pendo-sdk
yarn add rn-pendo-sdk
```


<!-- Sent from Reviewable.io -->

2023-11-22 09:34 UTC, udilevin requested changes
> Reviewed 1 of 11 files at r1, 1 of 22 files at r3, 6 of 18 files at r4, 2 of 4 files at r9, 2 of 14 files at r10, 4 of 7 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: 10 of 27 files reviewed, 8 unresolved discussions (waiting on @MikePendo, @noambartouv, @randmaayan, and @TehilaTaub)

___
*[`android-integration/flutter-android.md` line 3 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqIGx307xC0uanEd8O:-NjqIGx307xC0uanEd8P:bz38qow) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/android-integration/flutter-android.md#L3)):*
> ```Markdown
> # Flutter
> 
> >[!IMPORTANT]
> ```

Don't think we should mention codeless solution.. @naorlevi ?
___
*[`android-integration/rnn-android.md` line 5 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqMG74ECtpx87Fi1OZ:-NjqMG74ECtpx87Fi1O_:b8g7nnh) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/android-integration/rnn-android.md#L5)):*
Like expo we should probably mention here :100: 
Pendo supports codeless solution .... using React Native Navigation 6+.<br>
>- For the codeless solution to work, all the elements *MUST be wrapped in react-native ui components*<br>
___
*[`ios-integration/flutter-ios.md` line 3 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqMh0tB8XRioUX_b3_:-NjqMh0tB8XRioUX_b3a:b-6ois93) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/ios-integration/flutter-ios.md#L3)):*
> ```Markdown
> # Flutter
> 
> >[!IMPORTANT]
> ```

Not sure we should mention codeless solution  here
___
*[`ios-integration/rn-ios.md` line 5 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqN1t11v55z5WinKPn:-NjqN1t11v55z5WinKPo:b33q7wu) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/ios-integration/rn-ios.md#L5)):*
> ```Markdown
> >[!NOTE]
> >Pendo now supports Expo SDK 41-48. Follow [Expo Integration](/ios-integration/expo_rn-ios.md).
> ```

Like with Expo, we should probably mention here:  
Pendo supports RN using react-navigation 5+.  
  
For the codeless solution to work, all the elements _MUST be wrapped in react-native ui components_.  
  
As with other analytics tools, we are dependent on react-navigation [screen change callbacks](https://reactnavigation.org/docs/screen-tracking/)  
which means that codeless tracking analytics is available for screen components only.
___
*[`ios-integration/rn-ios.md` line 11 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqN4I13mG1xW86jLz7:-NjqN4I13mG1xW86jLz8:b5991f6) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/ios-integration/rn-ios.md#L11)):*
> ```Markdown
> 
>     Using NPM:
> ```

you can use the same terms and style like expo:  
use one of your package managers

```
npm i rn-pendo-sdk
yarn add rn-pendo-sdk
```


<!-- Sent from Reviewable.io -->

2023-11-22 09:39 UTC, udilevin requested changes
> Reviewed 1 of 7 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: 11 of 27 files reviewed, 10 unresolved discussions (waiting on @MikePendo, @noambartouv, @randmaayan, and @TehilaTaub)

___
*[`ios-integration/rnn-ios.md` line 5 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqNl7q9jmLtzmLdsym:-NjqNl7q9jmLtzmLdsyn:b-hjnsjg) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/ios-integration/rnn-ios.md#L5)):*
ike expo we should probably mention here 
Pendo supports codeless solution .... using React Native Navigation 6+.  

> -   For the codeless solution to work, all the elements _MUST be wrapped in react-native ui components_
___
*[`ios-integration/rnn-ios.md` line 10 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqNnqOCvlJP0WN0ptf:-NjqNnqOCvlJP0WN0ptg:b5991f6) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/ios-integration/rnn-ios.md#L10)):*
> ```Markdown
> 
> 1. In the **application folder**, run the following command:
> ```

you can use the same terms and style like expo:  
use one of your package managers

```
npm i rn-pendo-sdk
yarn add rn-pendo-sdk
```


<!-- Sent from Reviewable.io -->

2023-11-22 09:43 UTC, udilevin commented
*[`migration-docs/maui-2.x-to-3.x-migration.md` line 26 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqP0UB0CcoD-hvjw4G:-NjqP0UC7AzgO3lylhEW:bb7olmm) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/migration-docs/maui-2.x-to-3.x-migration.md#L26)):*
> ```Markdown
> <!--- new row --->
> 
> <tr>
> ```

Not sure how Java version applies to Xamarin or Maui...think this part can be removed (can't find anywhere we can define Java in Visual Studio


<!-- Sent from Reviewable.io -->

2023-11-22 09:43 UTC, udilevin commented
*[`migration-docs/maui-2.x-to-3.x-migration.md` line 26 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqP0UB0CcoD-hvjw4G:-NjqP0UC7AzgO3lylhEW:bb7olmm) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/migration-docs/maui-2.x-to-3.x-migration.md#L26)):*
> ```Markdown
> <!--- new row --->
> 
> <tr>
> ```

Not sure how Java version applies to Xamarin or Maui...think this part can be removed (can't find anywhere we can define Java in Visual Studio


<!-- Sent from Reviewable.io -->

2023-11-22 09:45 UTC, udilevin commented
*[`migration-docs/README.md` line 3 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqPbeg8u3lPPFhl6tC:-NjqPbeg8u3lPPFhl6tD:b-ev7sz7) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/migration-docs/README.md#L3)):*
> ```Markdown
> # Migrating from version 2.x to version 3.x
> 
> >[!NOTE]
> ```

You don't have to create a new app when moving from Binding to Forms (You will need to use both iOS and Android keys in the shared plugin). 
They will need to update all pages. 


<!-- Sent from Reviewable.io -->

2023-11-22 09:45 UTC, udilevin commented
*[`migration-docs/xamarin-forms-2.x-to-3.x-migration.md` line 23 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqPwAdBqZwa91Dq9zo:-NjqPwAdBqZwa91Dq9zp:b-87i6xr) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/migration-docs/xamarin-forms-2.x-to-3.x-migration.md#L23)):*
> ```Markdown
> 
> <!--- new row --->
> ```

Don't think that JAVA version is relevant to Xamarin Forms


<!-- Sent from Reviewable.io -->

2023-11-22 14:35 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: 11 of 27 files reviewed, 11 unresolved discussions (waiting on @MikePendo, @randmaayan, @TehilaTaub, and @udilevin)

___
*[`android-integration/native-android.md` line 26 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqJx1f2XxMtXloACxK:-NjrNdMdDsfCHZDoQE3m:bs7wupc) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/android-integration/native-android.md#L26)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

needs to be 3.0.+
</blockquote></details>

Done.w
___
*[`ios-integration/rn-ios.md` line 11 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqN4I13mG1xW86jLz7:-NjrR6Px5SmskA8bbWJt:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/ios-integration/rn-ios.md#L11)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

you can use the same terms and style like expo:  
use one of your package managers

```
npm i rn-pendo-sdk
yarn add rn-pendo-sdk
```
</blockquote></details>

Done.
___
*[`ios-integration/rnn-ios.md` line 10 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqNnqOCvlJP0WN0ptf:-NjrR86X6hnxwnYfcATF:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/ios-integration/rnn-ios.md#L10)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

you can use the same terms and style like expo:  
use one of your package managers

```
npm i rn-pendo-sdk
yarn add rn-pendo-sdk
```
</blockquote></details>

Done.
___
*[`migration-docs/maui-2.x-to-3.x-migration.md` line 26 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqP0UB0CcoD-hvjw4G:-NjrRNhZ1qEZfoiKpW8y:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/migration-docs/maui-2.x-to-3.x-migration.md#L26)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Not sure how Java version applies to Xamarin or Maui...think this part can be removed (can't find anywhere we can define Java in Visual Studio
</blockquote></details>

Done.
___
*[`migration-docs/README.md` line 3 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqPbeg8u3lPPFhl6tC:-NjrSAnN6ws4W4zpVynm:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/migration-docs/README.md#L3)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

You don't have to create a new app when moving from Binding to Forms (You will need to use both iOS and Android keys in the shared plugin). 
They will need to update all pages.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-22 14:35 UTC, pendo-ops commented
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[1bd3b8c](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/1bd3b8c60037fb5bcf19fe676257d6e0117dc6c5)
[757478b](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/757478bc2a0a4ad361d339987f5b012c32a3444e)
[d5ca623](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/d5ca6233a6b49bb4d0dfe36d6654e0d10efb6ee5)
[0d38671](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/0d38671236011583820b25da19e032c1c3560ad8)
[10fe652](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/10fe652ab95a006dfd4446e47b6b63cc73134a03)
[4bfe8b1](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/4bfe8b135cd02daa73cf0efca35a872982c67bcf)
[3c2dfbd](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/3c2dfbdc06c39398a62093b419ea9d5775c3ed24)
[f1951e2](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/f1951e2de1eb2a490408a063c887104309b0c39c)
[f820c76](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/f820c76860c719cd34d82dd55d1ad969aaaa2b01)
[2b72ecd](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/2b72ecdc74a7572e974744230aab596cb87cf391)

2023-11-22 14:52 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: 7 of 27 files reviewed, 11 unresolved discussions (waiting on @MikePendo, @naorlevi, @randmaayan, @TehilaTaub, and @udilevin)

___
*[`android-integration/flutter-android.md` line 3 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqIGx307xC0uanEd8O:-NjrW-Lw87QgBSzVRj6a:bpwd3un) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/android-integration/flutter-android.md#L3)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Don't think we should mention codeless solution.. @naorlevi ?
</blockquote></details>

Discussed with Naor. He said to keep and we will update it in the future when things change 
___
*[`ios-integration/flutter-ios.md` line 3 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqMh0tB8XRioUX_b3_:-NjrWAxA2-edm7ezCRzD:bpwd3un) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/ios-integration/flutter-ios.md#L3)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Not sure we should mention codeless solution  here
</blockquote></details>

Discussed with Naor. He said to keep and we will update it in the future when things change 


<!-- Sent from Reviewable.io -->

2023-11-22 16:14 UTC, randmaayan reviewed
> Reviewed 1 of 18 files at r4, 2 of 6 files at r5, 9 of 13 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: 18 of 27 files reviewed, 20 unresolved discussions (waiting on @MikePendo, @naorlevi, @noambartouv, @TehilaTaub, and @udilevin)

___
*[`android-integration/android_sdk_manual_installation.md` line 32 at r15](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-Njrk3f47WAw0HxtB4pm:-Njrk3f47WAw0HxtB4pn:bqzhjck) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/2b72ecdc74a7572e974744230aab596cb87cf391/android-integration/android_sdk_manual_installation.md#L32)):*
> ```Markdown
> ## Troubleshooting
> 
> - For technical issues please [review open issues](https://github.com/pendo-io/pendo-mobile-sdk/issues) or [submit a new issue](https://github.com/pendo-io/pendo-mobile-sdk/issues).
> ```

please update the troubleshooting section here as well. 
___
*[`android-integration/flutter-android.md` line 4 at r15](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjrkY-T3F8S0G9MqL3r:-NjrkY-T3F8S0G9MqL3s:b-tbav15) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/2b72ecdc74a7572e974744230aab596cb87cf391/android-integration/flutter-android.md#L4)):*
> ```Markdown
> 
> >[!IMPORTANT]
> >Pendo supports track events only in Flutter, the codeless solution is still in progress
> ```

Pendo supports only a Track Event solution in flutter. 
___
*[`android-integration/rn-android.md` line 187 at r15](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjrlKWv9YOiL_1il1I0:-NjrlKWv9YOiL_1il1I1:b-96q8kb) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/2b72ecdc74a7572e974744230aab596cb87cf391/android-integration/rn-android.md#L187)):*
> ```Markdown
> - For technical issues please [review open issues](https://github.com/pendo-io/pendo-mobile-sdk/issues) or [submit a new issue](https://github.com/pendo-io/pendo-mobile-sdk/issues).
> - Release notes can be found [here](https://developers.pendo.io/category/mobile-sdk/).
> - For Dex issues with Android applications refer to this [resource](https://developer.android.com/studio/build/multidex).
> ```

remove the dex issues.
___
*[`android-integration/rnn-android.md` line 164 at r15](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjrlHQ3DAmgqCM0DV9v:-NjrlHQ47ugWw3YfuOq-:b-pi14gn) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/2b72ecdc74a7572e974744230aab596cb87cf391/android-integration/rnn-android.md#L164)):*
> ```Markdown
> - For technical issues please [review open issues](https://github.com/pendo-io/pendo-mobile-sdk/issues) or [submit a new issue](https://github.com/pendo-io/pendo-mobile-sdk/issues).
> - Release notes can be found [here](https://developers.pendo.io/category/mobile-sdk/).
> - For Dex issues with Android applications refer to this [resource](https://developer.android.com/studio/build/multidex).
> ```

remove the dex issues
___
*[`android-integration/xamarin_forms-android.md` line 158 at r15](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjrlURUB7ZmqCqbk_xw:-NjrlURUB7ZmqCqbk_xx:b2ni12q) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/2b72ecdc74a7572e974744230aab596cb87cf391/android-integration/xamarin_forms-android.md#L158)):*
> ```Markdown
> - For technical issues please [review open issues](https://github.com/pendo-io/pendo-mobile-sdk/issues) or [submit a new issue](https://github.com/pendo-io/pendo-mobile-sdk/issues).
> - Release notes can be found [here](https://developers.pendo.io/category/mobile-sdk/).
> - For Dex issues with Android applications refer to this [resource](https://developer.android.com/studio/build/multidex).
> ```

dex
___
*[`ios-integration/flutter-ios.md` line 4 at r15](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-Njrlry97S3xMq1jtYqs:-Njrlry97S3xMq1jtYqt:b-djpnws) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/2b72ecdc74a7572e974744230aab596cb87cf391/ios-integration/flutter-ios.md#L4)):*
> ```Markdown
> 
> >[!IMPORTANT]
> >Important: Pendo supports track events only in Flutter, the codeless solution is still in progress
> ```

same comment as the other android flutter
___
*[`ios-integration/native-ios.md` line 18 at r15](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjrlyPR2IFC4Ke81q4I:-NjrlyPR2IFC4Ke81q4J:b9bi3a3) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/2b72ecdc74a7572e974744230aab596cb87cf391/ios-integration/native-ios.md#L18)):*
> ```Markdown
> 
> >[!IMPORTANT]
> ><b>SwiftUI</b> full support full codeless solution is supported from `iOS 15`. <br> <b>SwiftUI</b> screen navigation tracking is available from `iOS 13`.
> ```

full support full codeless? 
___
*[`ios-integration/native-ios.md` line 106 at r15](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjrmBbj1_NfRqBqmZ0h:-NjrmBbj1_NfRqBqmZ0i:b-3nbex6) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/2b72ecdc74a7572e974744230aab596cb87cf391/ios-integration/native-ios.md#L106)):*
> ```Markdown
> ## Step 3. Start a new session to track a visitor and to display guides
> 
> To begin tracking a visitor's analytics and display guides call the `startSession` API. The call to the `startSession` API can be conducted immediately after calling the `setup` API or anywhere else in the code, such as completing the log in process of your app. To begin a session for an anonymous visitor, pass ```nil``` as the visitor id. You can call the `startSession` API more than once and transition from an anonymous session to an identified session (or even switch between multiple identified sessions). 
> ```

login is one word.
can we add some line breaks here? 
___
*[`migration-docs/README.md` line 4 at r15](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjrnG-K7HJUc522SmJb:-NjrnG-K7HJUc522SmJc:b-6y9jpt) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/2b72ecdc74a7572e974744230aab596cb87cf391/migration-docs/README.md#L4)):*
> ```Markdown
> 
> >[!NOTE]
> >Xamarin iOS and Xamarin Android are no longer supported in 3.x. Please use the SDK for MAUI or Xamarin Forms. You can continue using your existing Android and iOS Pendo Apps, but make sure to pass in the correct App Key per platform and to update all of your tagged pages.
> ```

App key -> Api key


<!-- Sent from Reviewable.io -->

2023-11-22 16:37 UTC, pendo-ops commented
Failed pendo.io/jira-ref check. Please correct Jira references in the following commits:

[1bd3b8c](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/1bd3b8c60037fb5bcf19fe676257d6e0117dc6c5)
[757478b](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/757478bc2a0a4ad361d339987f5b012c32a3444e)
[d5ca623](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/d5ca6233a6b49bb4d0dfe36d6654e0d10efb6ee5)
[0d38671](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/0d38671236011583820b25da19e032c1c3560ad8)
[10fe652](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/10fe652ab95a006dfd4446e47b6b63cc73134a03)
[4bfe8b1](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/4bfe8b135cd02daa73cf0efca35a872982c67bcf)
[3c2dfbd](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/3c2dfbdc06c39398a62093b419ea9d5775c3ed24)
[f1951e2](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/f1951e2de1eb2a490408a063c887104309b0c39c)
[f820c76](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/f820c76860c719cd34d82dd55d1ad969aaaa2b01)
[2b72ecd](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/2b72ecdc74a7572e974744230aab596cb87cf391)
[a533467](https://github.com/pendo-io/pendo-mobile-sdk/pull/79/commits/a5334676c2cf43ca3a8bbba87bea6983c55afe00)

2023-11-22 16:49 UTC, noambartouv reviewed
> *[Reviewable](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79)* status: 7 of 27 files reviewed, 8 unresolved discussions (waiting on @MikePendo, @randmaayan, @TehilaTaub, and @udilevin)

___
*[`android-integration/rnn-android.md` line 5 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqMG74ECtpx87Fi1OZ:-NjruK5UCXB6pk0qNV2s:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/android-integration/rnn-android.md#L5)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Like expo we should probably mention here :100: 
Pendo supports codeless solution .... using React Native Navigation 6+.<br>
>- For the codeless solution to work, all the elements *MUST be wrapped in react-native ui components*<br>
</blockquote></details>

Done.
___
*[`ios-integration/rn-ios.md` line 5 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqN1t11v55z5WinKPn:-Njrutaq-b1zR2tQqKpR:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/ios-integration/rn-ios.md#L5)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

Like with Expo, we should probably mention here:  
Pendo supports RN using react-navigation 5+.  
  
For the codeless solution to work, all the elements _MUST be wrapped in react-native ui components_.  
  
As with other analytics tools, we are dependent on react-navigation [screen change callbacks](https://reactnavigation.org/docs/screen-tracking/)  
which means that codeless tracking analytics is available for screen components only.
</blockquote></details>

Done.
___
*[`ios-integration/rnn-ios.md` line 5 at r14](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/79#-NjqNl7q9jmLtzmLdsym:-NjruuK91_Lt_r3V-jrc:b-896fix) ([raw file](https://github.com/pendo-io/pendo-mobile-sdk/blob/f820c76860c719cd34d82dd55d1ad969aaaa2b01/ios-integration/rnn-ios.md#L5)):*
<details><summary><i>Previously, udilevin (Udi Levin) wrote…</i></summary><blockquote>

ike expo we should probably mention here 
Pendo supports codeless solution .... using React Native Navigation 6+.  

> -   For the codeless solution to work, all the elements _MUST be wrapped in react-native ui components_
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-22 19:41 UTC, noambartouv commented
[merge]

2023-11-22 19:41 UTC, pendo-ops commented
The merger (noambartouv) does not have permissions to merge this Pull Request. The creator of a Pull Request cannot merge that Pull Request.  Please have another team member merge it for you.

2023-11-22 19:50 UTC, MikePendo commented
[merge]

2023-11-22 19:50 UTC, merged

2023-11-22 19:50 UTC, pendo-ops commented
Some JIRA issue transitions/labels succeeded, but some didn't.
Total number of issues: 1
Issues that successfully transitioned/labeled: 0
Issues that weren't transitioned/labeled: 0
Problems encountered:


Branch APP-88967-3.0-updated-installation-instructions deleted